use ecom;
SELECT @companyId := 1, @createdBy := 1;
DROP VIEW IF EXISTS sms_report;
CREATE VIEW sms_report AS 
SELECT 
MESSAGE_DETAIL_ID,SENDER_ID,RECEIVER_ID,MESSAGE_DESCRIPTION,DELIVERY_ID,DELIVERY_STATUS,MESSAGE_ASSOCIATION_ID,
(SELECT MESSAGE_BUNDLE_COUNT FROM ecom.message where MESSAGE_ASSOCIATION_ID=MESSAGE_ID) As 'MESSAGE_BUNDLE_COUNT',
OUTLET_ASSOCICATION_ID,(select OUTLET_NAME from ecom.outlet where OUTLET_ASSOCICATION_ID=OUTLET_ID) As 'OUTLET_NAME',
DATE_FORMAT(CREATED_DATE,'%b %d %Y %h:%i %p')SMS_SENT_DATE,DATE(CREATED_DATE) as CREATED_DATE,
(select CONCAT(FIRST_NAME, ' ',LAST_NAME) from ecom.user where ecom.user.USER_ID=message_detail.CREATED_BY) AS 'SENDER_NAME',
coalesce((select FIRST_NAME  from ecom.contact where ecom.contact.CONTACT_ID=message_detail.RECEIVER_ID),'BULK') AS 'CUSTOMER_NAME',
COMPANY_ASSOCIATION_ID
FROM ecom.message_detail 
Order by  DATE(CREATED_DATE);

  INSERT INTO `ecom`.`message` ( `MESSAGE_BUNDLE_COUNT`, `PACKAGE_START_DATE`, `PACKAGE_END_DATE`, `PACKAGE_RENEW_DATE`, `MESSAGE_TEXT_LIMIT`, `VENDER_NAME`, `MASK_NAME`, `USER_ID`, `PASSWORD`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CREATED_BY`, `UPDATED_BY`, `COMPANY_ASSOCIATION_ID`, `OUTLET_ASSOCICATION_ID`) 
  VALUES ( '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '0', 'Brand', '8023', '923214823566', '9183', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, @createdBy, @createdBy, @companyId, @outletId);
 insert into ecom.menu ( MENU_NAME, ROLE_ASSOCIATION_ID, ACTION_TYPE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID	)
  values ('smsDetail', 	1, 'Page', 1, CURDATE(), CURDATE(), @createdBy,@createdBy,@companyId);

   insert into ecom.menu ( MENU_NAME, ROLE_ASSOCIATION_ID, ACTION_TYPE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID	)
    values ('smsDetail', 	2, 	'Page', 1, CURDATE(), CURDATE(), @createdBy,@createdBy,@companyId);

   insert into ecom.menu ( MENU_NAME, ROLE_ASSOCIATION_ID, ACTION_TYPE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID	)
   values ('smsDetail', 	3, 	'Page', 1, CURDATE(), CURDATE(), @createdBy,@createdBy,@companyId);
 
   insert into ecom.menu ( MENU_NAME, ROLE_ASSOCIATION_ID, ACTION_TYPE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID	)
   values ('sendSms', 	1, 'Page', 1, CURDATE(), CURDATE(), @createdBy,@createdBy,@companyId);

   insert into ecom.menu ( MENU_NAME, ROLE_ASSOCIATION_ID, ACTION_TYPE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID	)
    values ('sendSms', 	2, 	'Page', 1, CURDATE(), CURDATE(), @createdBy,@createdBy,@companyId);

   insert into ecom.menu ( MENU_NAME, ROLE_ASSOCIATION_ID, ACTION_TYPE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID	)
   values ('sendSms', 	3, 	'Page', 1, CURDATE(), CURDATE(), @createdBy,@createdBy,@companyId);
