
use ecom;
DELIMITER $$
 
CREATE TRIGGER after_product_Var_update
AFTER UPDATE
ON product_variant FOR EACH ROW
BEGIN
   
 update `mv_inventory_report`  set CURRENT_INVENTORY = new.CURRENT_INVENTORY,NET_PRICE =(((`New`.`SUPPLY_PRICE_EXCL_TAX` * `New`.`MARKUP_PRCT`) / 100) + `New`.`SUPPLY_PRICE_EXCL_TAX`) ,
STOCK_VALUE =(`New`.`SUPPLY_PRICE_EXCL_TAX` * `New`.`CURRENT_INVENTORY`),SUPPLY_PRICE_EXCL_TAX = New.SUPPLY_PRICE_EXCL_TAX,MARKUP_PRCT = New.MARKUP_PRCT,

 RETAIL_VALUE = ((((`New`.`SUPPLY_PRICE_EXCL_TAX` * `New`.`MARKUP_PRCT`) / 100) + `New`.`SUPPLY_PRICE_EXCL_TAX`) * `New`.`CURRENT_INVENTORY`)
 where id = new.PRODUCT_VARIANT_ID ;
    
END$$
 
DELIMITER ;