package com.dowhile;

// Generated Dec 18, 2017 8:15:51 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContactsSummmary generated by hbm2java
 */
@Entity
@Table(name = "contacts_summmary")
public class ContactsSummmary implements java.io.Serializable {

	private ContactsSummmaryId id;

	public ContactsSummmary() {
	}

	public ContactsSummmary(ContactsSummmaryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "contactId", column = @Column(name = "CONTACT_ID", nullable = false)),
			@AttributeOverride(name = "contactName", column = @Column(name = "CONTACT_NAME", length = 400)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FIRST_NAME", length = 200)),
			@AttributeOverride(name = "lastName", column = @Column(name = "LAST_NAME", length = 200)),
			@AttributeOverride(name = "companyName", column = @Column(name = "COMPANY_NAME", length = 100)),
			@AttributeOverride(name = "balance", column = @Column(name = "BALANCE", precision = 20, scale = 5)),
			@AttributeOverride(name = "phone", column = @Column(name = "PHONE", length = 256)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE", nullable = false, length = 19)),
			@AttributeOverride(name = "activeIndicator", column = @Column(name = "ACTIVE_INDICATOR", nullable = false)),
			@AttributeOverride(name = "outletAssociationId", column = @Column(name = "OUTLET_ASSOCIATION_ID", nullable = false)),
			@AttributeOverride(name = "companyAssociationId", column = @Column(name = "COMPANY_ASSOCIATION_ID", nullable = false)),
			@AttributeOverride(name = "lastUpdated", column = @Column(name = "LAST_UPDATED", nullable = false, length = 19)),
			@AttributeOverride(name = "contactGroup", column = @Column(name = "CONTACT_GROUP", length = 200)),
			@AttributeOverride(name = "contactType", column = @Column(name = "CONTACT_TYPE", nullable = false, length = 250)) })
	public ContactsSummmaryId getId() {
		return this.id;
	}

	public void setId(ContactsSummmaryId id) {
		this.id = id;
	}

}
