package com.dowhile;

// Generated Dec 5, 2017 5:08:49 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExpenseType generated by hbm2java
 */
@Entity
@Table(name = "expense_type")
public class ExpenseType implements java.io.Serializable {

	private Integer expenseTypeId;
	private Company company;
	private String expenseTypeName;
	private Integer countryAssocicationId;
	private boolean activeIndicator;
	private Date createdDate;
	private Date lastUpdated;
	private Integer createdBy;
	private Integer updatedBy;
	private Set<CashManagment> cashManagments = new HashSet<CashManagment>(0);

	public ExpenseType() {
	}

	public ExpenseType(Company company, String expenseTypeName,
			boolean activeIndicator, Date createdDate, Date lastUpdated) {
		this.company = company;
		this.expenseTypeName = expenseTypeName;
		this.activeIndicator = activeIndicator;
		this.createdDate = createdDate;
		this.lastUpdated = lastUpdated;
	}

	public ExpenseType(Company company, String expenseTypeName,
			Integer countryAssocicationId, boolean activeIndicator,
			Date createdDate, Date lastUpdated, Integer createdBy,
			Integer updatedBy, Set<CashManagment> cashManagments) {
		this.company = company;
		this.expenseTypeName = expenseTypeName;
		this.countryAssocicationId = countryAssocicationId;
		this.activeIndicator = activeIndicator;
		this.createdDate = createdDate;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.cashManagments = cashManagments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EXPENSE_TYPE_ID", unique = true, nullable = false)
	public Integer getExpenseTypeId() {
		return this.expenseTypeId;
	}

	public void setExpenseTypeId(Integer expenseTypeId) {
		this.expenseTypeId = expenseTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ASSOCIATION_ID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "EXPENSE_TYPE_NAME", nullable = false, length = 200)
	public String getExpenseTypeName() {
		return this.expenseTypeName;
	}

	public void setExpenseTypeName(String expenseTypeName) {
		this.expenseTypeName = expenseTypeName;
	}

	@Column(name = "COUNTRY_ASSOCICATION_ID")
	public Integer getCountryAssocicationId() {
		return this.countryAssocicationId;
	}

	public void setCountryAssocicationId(Integer countryAssocicationId) {
		this.countryAssocicationId = countryAssocicationId;
	}

	@Column(name = "ACTIVE_INDICATOR", nullable = false)
	public boolean isActiveIndicator() {
		return this.activeIndicator;
	}

	public void setActiveIndicator(boolean activeIndicator) {
		this.activeIndicator = activeIndicator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expenseType")
	public Set<CashManagment> getCashManagments() {
		return this.cashManagments;
	}

	public void setCashManagments(Set<CashManagment> cashManagments) {
		this.cashManagments = cashManagments;
	}

}
