package com.dowhile;
// Generated May 8, 2019 8:28:21 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventoryCountVId generated by hbm2java
 */
@Embeddable
public class InventoryCountVId  implements java.io.Serializable {


     private int inventoryCountId;
     private String inventoryCountRefNo;
     private int statusAssocicationId;
     private int outletAssocicationId;
     private Integer expectedProdQty;
     private Integer countedProdQty;
     private Integer countDiff;
     private BigDecimal supplyPriceExp;
     private BigDecimal retailPriceExp;
     private BigDecimal priceDiff;
     private BigDecimal supplyPriceCounted;
     private BigDecimal retailPriceCounted;
     private String remarks;
     private int inventoryCountTypeAssocicationId;
     private int activeIndicator;
     private byte[] createdDate;
     private byte[] lastUpdated;
     private Integer createdBy;
     private Integer updatedBy;
     private int companyAssociationId;
     private String statusDesc;
     private String outlet;
     private String company;

    public InventoryCountVId() {
    }

	
    public InventoryCountVId(int inventoryCountId, int statusAssocicationId, int outletAssocicationId, int inventoryCountTypeAssocicationId, int activeIndicator, byte[] createdDate, byte[] lastUpdated, int companyAssociationId) {
        this.inventoryCountId = inventoryCountId;
        this.statusAssocicationId = statusAssocicationId;
        this.outletAssocicationId = outletAssocicationId;
        this.inventoryCountTypeAssocicationId = inventoryCountTypeAssocicationId;
        this.activeIndicator = activeIndicator;
        this.createdDate = createdDate;
        this.lastUpdated = lastUpdated;
        this.companyAssociationId = companyAssociationId;
    }
    public InventoryCountVId(int inventoryCountId, String inventoryCountRefNo, int statusAssocicationId, int outletAssocicationId, Integer expectedProdQty, Integer countedProdQty, Integer countDiff, BigDecimal supplyPriceExp, BigDecimal retailPriceExp, BigDecimal priceDiff, BigDecimal supplyPriceCounted, BigDecimal retailPriceCounted, String remarks, int inventoryCountTypeAssocicationId, int activeIndicator, byte[] createdDate, byte[] lastUpdated, Integer createdBy, Integer updatedBy, int companyAssociationId, String statusDesc, String outlet, String company) {
       this.inventoryCountId = inventoryCountId;
       this.inventoryCountRefNo = inventoryCountRefNo;
       this.statusAssocicationId = statusAssocicationId;
       this.outletAssocicationId = outletAssocicationId;
       this.expectedProdQty = expectedProdQty;
       this.countedProdQty = countedProdQty;
       this.countDiff = countDiff;
       this.supplyPriceExp = supplyPriceExp;
       this.retailPriceExp = retailPriceExp;
       this.priceDiff = priceDiff;
       this.supplyPriceCounted = supplyPriceCounted;
       this.retailPriceCounted = retailPriceCounted;
       this.remarks = remarks;
       this.inventoryCountTypeAssocicationId = inventoryCountTypeAssocicationId;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.companyAssociationId = companyAssociationId;
       this.statusDesc = statusDesc;
       this.outlet = outlet;
       this.company = company;
    }
   


    @Column(name="INVENTORY_COUNT_ID", nullable=false)
    public int getInventoryCountId() {
        return this.inventoryCountId;
    }
    
    public void setInventoryCountId(int inventoryCountId) {
        this.inventoryCountId = inventoryCountId;
    }


    @Column(name="INVENTORY_COUNT_REF_NO", length=45)
    public String getInventoryCountRefNo() {
        return this.inventoryCountRefNo;
    }
    
    public void setInventoryCountRefNo(String inventoryCountRefNo) {
        this.inventoryCountRefNo = inventoryCountRefNo;
    }


    @Column(name="STATUS_ASSOCICATION_ID", nullable=false)
    public int getStatusAssocicationId() {
        return this.statusAssocicationId;
    }
    
    public void setStatusAssocicationId(int statusAssocicationId) {
        this.statusAssocicationId = statusAssocicationId;
    }


    @Column(name="OUTLET_ASSOCICATION_ID", nullable=false)
    public int getOutletAssocicationId() {
        return this.outletAssocicationId;
    }
    
    public void setOutletAssocicationId(int outletAssocicationId) {
        this.outletAssocicationId = outletAssocicationId;
    }


    @Column(name="EXPECTED_PROD_QTY")
    public Integer getExpectedProdQty() {
        return this.expectedProdQty;
    }
    
    public void setExpectedProdQty(Integer expectedProdQty) {
        this.expectedProdQty = expectedProdQty;
    }


    @Column(name="COUNTED_PROD_QTY")
    public Integer getCountedProdQty() {
        return this.countedProdQty;
    }
    
    public void setCountedProdQty(Integer countedProdQty) {
        this.countedProdQty = countedProdQty;
    }


    @Column(name="COUNT_DIFF")
    public Integer getCountDiff() {
        return this.countDiff;
    }
    
    public void setCountDiff(Integer countDiff) {
        this.countDiff = countDiff;
    }


    @Column(name="SUPPLY_PRICE_EXP", precision=20)
    public BigDecimal getSupplyPriceExp() {
        return this.supplyPriceExp;
    }
    
    public void setSupplyPriceExp(BigDecimal supplyPriceExp) {
        this.supplyPriceExp = supplyPriceExp;
    }


    @Column(name="RETAIL_PRICE_EXP", precision=20)
    public BigDecimal getRetailPriceExp() {
        return this.retailPriceExp;
    }
    
    public void setRetailPriceExp(BigDecimal retailPriceExp) {
        this.retailPriceExp = retailPriceExp;
    }


    @Column(name="PRICE_DIFF", precision=20)
    public BigDecimal getPriceDiff() {
        return this.priceDiff;
    }
    
    public void setPriceDiff(BigDecimal priceDiff) {
        this.priceDiff = priceDiff;
    }


    @Column(name="SUPPLY_PRICE_COUNTED", precision=20)
    public BigDecimal getSupplyPriceCounted() {
        return this.supplyPriceCounted;
    }
    
    public void setSupplyPriceCounted(BigDecimal supplyPriceCounted) {
        this.supplyPriceCounted = supplyPriceCounted;
    }


    @Column(name="RETAIL_PRICE_COUNTED", precision=20)
    public BigDecimal getRetailPriceCounted() {
        return this.retailPriceCounted;
    }
    
    public void setRetailPriceCounted(BigDecimal retailPriceCounted) {
        this.retailPriceCounted = retailPriceCounted;
    }


    @Column(name="REMARKS", length=500)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


    @Column(name="INVENTORY_COUNT_TYPE_ASSOCICATION_ID", nullable=false)
    public int getInventoryCountTypeAssocicationId() {
        return this.inventoryCountTypeAssocicationId;
    }
    
    public void setInventoryCountTypeAssocicationId(int inventoryCountTypeAssocicationId) {
        this.inventoryCountTypeAssocicationId = inventoryCountTypeAssocicationId;
    }


    @Column(name="ACTIVE_INDICATOR", nullable=false)
    public int getActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(int activeIndicator) {
        this.activeIndicator = activeIndicator;
    }


    @Column(name="CREATED_DATE", nullable=false)
    public byte[] getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(byte[] createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="LAST_UPDATED", nullable=false)
    public byte[] getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(byte[] lastUpdated) {
        this.lastUpdated = lastUpdated;
    }


    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }


    @Column(name="UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }


    @Column(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public int getCompanyAssociationId() {
        return this.companyAssociationId;
    }
    
    public void setCompanyAssociationId(int companyAssociationId) {
        this.companyAssociationId = companyAssociationId;
    }


    @Column(name="STATUS_DESC", length=45)
    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }


    @Column(name="OUTLET", length=100)
    public String getOutlet() {
        return this.outlet;
    }
    
    public void setOutlet(String outlet) {
        this.outlet = outlet;
    }


    @Column(name="COMPANY", length=256)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InventoryCountVId) ) return false;
		 InventoryCountVId castOther = ( InventoryCountVId ) other; 
         
		 return (this.getInventoryCountId()==castOther.getInventoryCountId())
 && ( (this.getInventoryCountRefNo()==castOther.getInventoryCountRefNo()) || ( this.getInventoryCountRefNo()!=null && castOther.getInventoryCountRefNo()!=null && this.getInventoryCountRefNo().equals(castOther.getInventoryCountRefNo()) ) )
 && (this.getStatusAssocicationId()==castOther.getStatusAssocicationId())
 && (this.getOutletAssocicationId()==castOther.getOutletAssocicationId())
 && ( (this.getExpectedProdQty()==castOther.getExpectedProdQty()) || ( this.getExpectedProdQty()!=null && castOther.getExpectedProdQty()!=null && this.getExpectedProdQty().equals(castOther.getExpectedProdQty()) ) )
 && ( (this.getCountedProdQty()==castOther.getCountedProdQty()) || ( this.getCountedProdQty()!=null && castOther.getCountedProdQty()!=null && this.getCountedProdQty().equals(castOther.getCountedProdQty()) ) )
 && ( (this.getCountDiff()==castOther.getCountDiff()) || ( this.getCountDiff()!=null && castOther.getCountDiff()!=null && this.getCountDiff().equals(castOther.getCountDiff()) ) )
 && ( (this.getSupplyPriceExp()==castOther.getSupplyPriceExp()) || ( this.getSupplyPriceExp()!=null && castOther.getSupplyPriceExp()!=null && this.getSupplyPriceExp().equals(castOther.getSupplyPriceExp()) ) )
 && ( (this.getRetailPriceExp()==castOther.getRetailPriceExp()) || ( this.getRetailPriceExp()!=null && castOther.getRetailPriceExp()!=null && this.getRetailPriceExp().equals(castOther.getRetailPriceExp()) ) )
 && ( (this.getPriceDiff()==castOther.getPriceDiff()) || ( this.getPriceDiff()!=null && castOther.getPriceDiff()!=null && this.getPriceDiff().equals(castOther.getPriceDiff()) ) )
 && ( (this.getSupplyPriceCounted()==castOther.getSupplyPriceCounted()) || ( this.getSupplyPriceCounted()!=null && castOther.getSupplyPriceCounted()!=null && this.getSupplyPriceCounted().equals(castOther.getSupplyPriceCounted()) ) )
 && ( (this.getRetailPriceCounted()==castOther.getRetailPriceCounted()) || ( this.getRetailPriceCounted()!=null && castOther.getRetailPriceCounted()!=null && this.getRetailPriceCounted().equals(castOther.getRetailPriceCounted()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && (this.getInventoryCountTypeAssocicationId()==castOther.getInventoryCountTypeAssocicationId())
 && (this.getActiveIndicator()==castOther.getActiveIndicator())
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && Arrays.equals(this.getCreatedDate(), castOther.getCreatedDate()) ) )
 && ( (this.getLastUpdated()==castOther.getLastUpdated()) || ( this.getLastUpdated()!=null && castOther.getLastUpdated()!=null && Arrays.equals(this.getLastUpdated(), castOther.getLastUpdated()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && (this.getCompanyAssociationId()==castOther.getCompanyAssociationId())
 && ( (this.getStatusDesc()==castOther.getStatusDesc()) || ( this.getStatusDesc()!=null && castOther.getStatusDesc()!=null && this.getStatusDesc().equals(castOther.getStatusDesc()) ) )
 && ( (this.getOutlet()==castOther.getOutlet()) || ( this.getOutlet()!=null && castOther.getOutlet()!=null && this.getOutlet().equals(castOther.getOutlet()) ) )
 && ( (this.getCompany()==castOther.getCompany()) || ( this.getCompany()!=null && castOther.getCompany()!=null && this.getCompany().equals(castOther.getCompany()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInventoryCountId();
         result = 37 * result + ( getInventoryCountRefNo() == null ? 0 : this.getInventoryCountRefNo().hashCode() );
         result = 37 * result + this.getStatusAssocicationId();
         result = 37 * result + this.getOutletAssocicationId();
         result = 37 * result + ( getExpectedProdQty() == null ? 0 : this.getExpectedProdQty().hashCode() );
         result = 37 * result + ( getCountedProdQty() == null ? 0 : this.getCountedProdQty().hashCode() );
         result = 37 * result + ( getCountDiff() == null ? 0 : this.getCountDiff().hashCode() );
         result = 37 * result + ( getSupplyPriceExp() == null ? 0 : this.getSupplyPriceExp().hashCode() );
         result = 37 * result + ( getRetailPriceExp() == null ? 0 : this.getRetailPriceExp().hashCode() );
         result = 37 * result + ( getPriceDiff() == null ? 0 : this.getPriceDiff().hashCode() );
         result = 37 * result + ( getSupplyPriceCounted() == null ? 0 : this.getSupplyPriceCounted().hashCode() );
         result = 37 * result + ( getRetailPriceCounted() == null ? 0 : this.getRetailPriceCounted().hashCode() );
         result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         result = 37 * result + this.getInventoryCountTypeAssocicationId();
         result = 37 * result + this.getActiveIndicator();
         result = 37 * result + ( getCreatedDate() == null ? 0 : Arrays.hashCode(this.getCreatedDate()) );
         result = 37 * result + ( getLastUpdated() == null ? 0 : Arrays.hashCode(this.getLastUpdated()) );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + this.getCompanyAssociationId();
         result = 37 * result + ( getStatusDesc() == null ? 0 : this.getStatusDesc().hashCode() );
         result = 37 * result + ( getOutlet() == null ? 0 : this.getOutlet().hashCode() );
         result = 37 * result + ( getCompany() == null ? 0 : this.getCompany().hashCode() );
         return result;
   }   


}


