package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PriceBookDetailSummary generated by hbm2java
 */
@Entity
@Table(name="Price_Book_Detail_Summary"
    ,catalog="ecom"
)
public class PriceBookDetailSummary  implements java.io.Serializable {


     private PriceBookDetailSummaryId id;

    public PriceBookDetailSummary() {
    }

    public PriceBookDetailSummary(PriceBookDetailSummaryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="priceBookDetailId", column=@Column(name="PRICE_BOOK_DETAIL_ID", nullable=false) ), 
        @AttributeOverride(name="priceBookAssocicationId", column=@Column(name="PRICE_BOOK_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="productAssocicationId", column=@Column(name="PRODUCT_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="uuid", column=@Column(name="UUID", nullable=false, length=500) ), 
        @AttributeOverride(name="productName", column=@Column(name="PRODUCT_NAME", length=500) ), 
        @AttributeOverride(name="productVarientAssocicationId", column=@Column(name="PRODUCT_VARIENT_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="variantAttributeName", column=@Column(name="VARIANT_ATTRIBUTE_NAME", length=200) ), 
        @AttributeOverride(name="supplyPrice", column=@Column(name="SUPPLY_PRICE", nullable=false, precision=20) ), 
        @AttributeOverride(name="markup", column=@Column(name="MARKUP", nullable=false, precision=8, scale=5) ), 
        @AttributeOverride(name="discount", column=@Column(name="DISCOUNT", nullable=false, precision=8, scale=5) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY", nullable=false) ), 
        @AttributeOverride(name="updatedBy", column=@Column(name="UPDATED_BY", nullable=false) ), 
        @AttributeOverride(name="salesTaxAssociationId", column=@Column(name="SALES_TAX_ASSOCIATION_ID", nullable=false) ), 
        @AttributeOverride(name="companyAssociationId", column=@Column(name="COMPANY_ASSOCIATION_ID", nullable=false) ) } )
    public PriceBookDetailSummaryId getId() {
        return this.id;
    }
    
    public void setId(PriceBookDetailSummaryId id) {
        this.id = id;
    }




}


