package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PriceBookDetailSummaryId generated by hbm2java
 */
@Embeddable
public class PriceBookDetailSummaryId  implements java.io.Serializable {


     private int priceBookDetailId;
     private int priceBookAssocicationId;
     private int productAssocicationId;
     private String uuid;
     private String productName;
     private long productVarientAssocicationId;
     private String variantAttributeName;
     private BigDecimal supplyPrice;
     private BigDecimal markup;
     private BigDecimal discount;
     private int createdBy;
     private int updatedBy;
     private int salesTaxAssociationId;
     private int companyAssociationId;

    public PriceBookDetailSummaryId() {
    }

	
    public PriceBookDetailSummaryId(int priceBookDetailId, int priceBookAssocicationId, int productAssocicationId, String uuid, long productVarientAssocicationId, BigDecimal supplyPrice, BigDecimal markup, BigDecimal discount, int createdBy, int updatedBy, int salesTaxAssociationId, int companyAssociationId) {
        this.priceBookDetailId = priceBookDetailId;
        this.priceBookAssocicationId = priceBookAssocicationId;
        this.productAssocicationId = productAssocicationId;
        this.uuid = uuid;
        this.productVarientAssocicationId = productVarientAssocicationId;
        this.supplyPrice = supplyPrice;
        this.markup = markup;
        this.discount = discount;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.salesTaxAssociationId = salesTaxAssociationId;
        this.companyAssociationId = companyAssociationId;
    }
    public PriceBookDetailSummaryId(int priceBookDetailId, int priceBookAssocicationId, int productAssocicationId, String uuid, String productName, long productVarientAssocicationId, String variantAttributeName, BigDecimal supplyPrice, BigDecimal markup, BigDecimal discount, int createdBy, int updatedBy, int salesTaxAssociationId, int companyAssociationId) {
       this.priceBookDetailId = priceBookDetailId;
       this.priceBookAssocicationId = priceBookAssocicationId;
       this.productAssocicationId = productAssocicationId;
       this.uuid = uuid;
       this.productName = productName;
       this.productVarientAssocicationId = productVarientAssocicationId;
       this.variantAttributeName = variantAttributeName;
       this.supplyPrice = supplyPrice;
       this.markup = markup;
       this.discount = discount;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.salesTaxAssociationId = salesTaxAssociationId;
       this.companyAssociationId = companyAssociationId;
    }
   


    @Column(name="PRICE_BOOK_DETAIL_ID", nullable=false)
    public int getPriceBookDetailId() {
        return this.priceBookDetailId;
    }
    
    public void setPriceBookDetailId(int priceBookDetailId) {
        this.priceBookDetailId = priceBookDetailId;
    }


    @Column(name="PRICE_BOOK_ASSOCICATION_ID", nullable=false)
    public int getPriceBookAssocicationId() {
        return this.priceBookAssocicationId;
    }
    
    public void setPriceBookAssocicationId(int priceBookAssocicationId) {
        this.priceBookAssocicationId = priceBookAssocicationId;
    }


    @Column(name="PRODUCT_ASSOCICATION_ID", nullable=false)
    public int getProductAssocicationId() {
        return this.productAssocicationId;
    }
    
    public void setProductAssocicationId(int productAssocicationId) {
        this.productAssocicationId = productAssocicationId;
    }


    @Column(name="UUID", nullable=false, length=500)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    @Column(name="PRODUCT_NAME", length=500)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }


    @Column(name="PRODUCT_VARIENT_ASSOCICATION_ID", nullable=false)
    public long getProductVarientAssocicationId() {
        return this.productVarientAssocicationId;
    }
    
    public void setProductVarientAssocicationId(long productVarientAssocicationId) {
        this.productVarientAssocicationId = productVarientAssocicationId;
    }


    @Column(name="VARIANT_ATTRIBUTE_NAME", length=200)
    public String getVariantAttributeName() {
        return this.variantAttributeName;
    }
    
    public void setVariantAttributeName(String variantAttributeName) {
        this.variantAttributeName = variantAttributeName;
    }


    @Column(name="SUPPLY_PRICE", nullable=false, precision=20)
    public BigDecimal getSupplyPrice() {
        return this.supplyPrice;
    }
    
    public void setSupplyPrice(BigDecimal supplyPrice) {
        this.supplyPrice = supplyPrice;
    }


    @Column(name="MARKUP", nullable=false, precision=8, scale=5)
    public BigDecimal getMarkup() {
        return this.markup;
    }
    
    public void setMarkup(BigDecimal markup) {
        this.markup = markup;
    }


    @Column(name="DISCOUNT", nullable=false, precision=8, scale=5)
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }


    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }


    @Column(name="UPDATED_BY", nullable=false)
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }


    @Column(name="SALES_TAX_ASSOCIATION_ID", nullable=false)
    public int getSalesTaxAssociationId() {
        return this.salesTaxAssociationId;
    }
    
    public void setSalesTaxAssociationId(int salesTaxAssociationId) {
        this.salesTaxAssociationId = salesTaxAssociationId;
    }


    @Column(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public int getCompanyAssociationId() {
        return this.companyAssociationId;
    }
    
    public void setCompanyAssociationId(int companyAssociationId) {
        this.companyAssociationId = companyAssociationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PriceBookDetailSummaryId) ) return false;
		 PriceBookDetailSummaryId castOther = ( PriceBookDetailSummaryId ) other; 
         
		 return (this.getPriceBookDetailId()==castOther.getPriceBookDetailId())
 && (this.getPriceBookAssocicationId()==castOther.getPriceBookAssocicationId())
 && (this.getProductAssocicationId()==castOther.getProductAssocicationId())
 && ( (this.getUuid()==castOther.getUuid()) || ( this.getUuid()!=null && castOther.getUuid()!=null && this.getUuid().equals(castOther.getUuid()) ) )
 && ( (this.getProductName()==castOther.getProductName()) || ( this.getProductName()!=null && castOther.getProductName()!=null && this.getProductName().equals(castOther.getProductName()) ) )
 && (this.getProductVarientAssocicationId()==castOther.getProductVarientAssocicationId())
 && ( (this.getVariantAttributeName()==castOther.getVariantAttributeName()) || ( this.getVariantAttributeName()!=null && castOther.getVariantAttributeName()!=null && this.getVariantAttributeName().equals(castOther.getVariantAttributeName()) ) )
 && ( (this.getSupplyPrice()==castOther.getSupplyPrice()) || ( this.getSupplyPrice()!=null && castOther.getSupplyPrice()!=null && this.getSupplyPrice().equals(castOther.getSupplyPrice()) ) )
 && ( (this.getMarkup()==castOther.getMarkup()) || ( this.getMarkup()!=null && castOther.getMarkup()!=null && this.getMarkup().equals(castOther.getMarkup()) ) )
 && ( (this.getDiscount()==castOther.getDiscount()) || ( this.getDiscount()!=null && castOther.getDiscount()!=null && this.getDiscount().equals(castOther.getDiscount()) ) )
 && (this.getCreatedBy()==castOther.getCreatedBy())
 && (this.getUpdatedBy()==castOther.getUpdatedBy())
 && (this.getSalesTaxAssociationId()==castOther.getSalesTaxAssociationId())
 && (this.getCompanyAssociationId()==castOther.getCompanyAssociationId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPriceBookDetailId();
         result = 37 * result + this.getPriceBookAssocicationId();
         result = 37 * result + this.getProductAssocicationId();
         result = 37 * result + ( getUuid() == null ? 0 : this.getUuid().hashCode() );
         result = 37 * result + ( getProductName() == null ? 0 : this.getProductName().hashCode() );
         result = 37 * result + (int) this.getProductVarientAssocicationId();
         result = 37 * result + ( getVariantAttributeName() == null ? 0 : this.getVariantAttributeName().hashCode() );
         result = 37 * result + ( getSupplyPrice() == null ? 0 : this.getSupplyPrice().hashCode() );
         result = 37 * result + ( getMarkup() == null ? 0 : this.getMarkup().hashCode() );
         result = 37 * result + ( getDiscount() == null ? 0 : this.getDiscount().hashCode() );
         result = 37 * result + this.getCreatedBy();
         result = 37 * result + this.getUpdatedBy();
         result = 37 * result + this.getSalesTaxAssociationId();
         result = 37 * result + this.getCompanyAssociationId();
         return result;
   }   


}


