package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductTag generated by hbm2java
 */
@Entity
@Table(name="product_tag"
    ,catalog="ecom"
)
public class ProductTag  implements java.io.Serializable {


     private Integer productTagId;
     private Tag tag;
     private User userByCreatedBy;
     private User userByUpdatedBy;
     private Product product;
     private Company company;
     private String productTagUuid;
     private boolean activeIndicator;
     private Date createdDate;
     private Date lastUpdated;

    public ProductTag() {
    }

	
    public ProductTag(Tag tag, Product product, Company company, String productTagUuid, boolean activeIndicator, Date createdDate, Date lastUpdated) {
        this.tag = tag;
        this.product = product;
        this.company = company;
        this.productTagUuid = productTagUuid;
        this.activeIndicator = activeIndicator;
        this.createdDate = createdDate;
        this.lastUpdated = lastUpdated;
    }
    public ProductTag(Tag tag, User userByCreatedBy, User userByUpdatedBy, Product product, Company company, String productTagUuid, boolean activeIndicator, Date createdDate, Date lastUpdated) {
       this.tag = tag;
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.product = product;
       this.company = company;
       this.productTagUuid = productTagUuid;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PRODUCT_TAG_ID", unique=true, nullable=false)
    public Integer getProductTagId() {
        return this.productTagId;
    }
    
    public void setProductTagId(Integer productTagId) {
        this.productTagId = productTagId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TAG_ASSOCICATION_ID", nullable=false)
    public Tag getTag() {
        return this.tag;
    }
    
    public void setTag(Tag tag) {
        this.tag = tag;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATED_BY")
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UPDATED_BY")
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ASSOCICATION_ID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="PRODUCT_TAG_UUID", nullable=false, length=500)
    public String getProductTagUuid() {
        return this.productTagUuid;
    }
    
    public void setProductTagUuid(String productTagUuid) {
        this.productTagUuid = productTagUuid;
    }

    
    @Column(name="ACTIVE_INDICATOR", nullable=false)
    public boolean isActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(boolean activeIndicator) {
        this.activeIndicator = activeIndicator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


