package com.dowhile;
// Generated Feb 22, 2018 4:09:55 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPriceHistory generated by hbm2java
 */
@Entity
@Table(name="product_price_history"
    ,catalog="ecom"
)
public class ProductPriceHistory  implements java.io.Serializable {


    private Integer productPriceHistoryId;
    private Outlet outlet;
    private User userByCreatedBy;
    private User userByUpdatedBy;
    private Company company;
    private SalesTax salesTax;
    private int productId;
    private String productUuid;
    private Integer productVariantId;
    private String productVariantUuid;
    private String coCode;
    private String sroNumber;
    private String hsCode;
    private String description;
    private BigDecimal dollarRate;
    private BigDecimal DUnitValueDeclared;
    private BigDecimal DUnitValueAssessed;
    private BigDecimal DTotalValueDeclared;
    private BigDecimal DTotalValueAssessed;
    private BigDecimal PCustomValueDeclared;
    private BigDecimal PCustomValueAssessed;
    private BigDecimal numberOfUnits;
    private BigDecimal customDutyPrct;
    private BigDecimal customDutyValue;
    private BigDecimal salesTaxPrct;
    private BigDecimal salesTaxValue;
    private BigDecimal regularityDutyPrct;
    private BigDecimal regularityDutyValue;
    private BigDecimal additionalCustomDutyPrct;
    private BigDecimal additionalCustomDutyValue;
    private BigDecimal additionalSalesTaxPrct;
    private BigDecimal additionalSalesTaxValue;
    private BigDecimal excisePrct;
    private BigDecimal exciseValue;
    private BigDecimal totalValue;
    private BigDecimal itPrct;
    private BigDecimal itValue;
    private BigDecimal ftaPrct;
    private BigDecimal ftaValue;
    private String remarks;
    private Integer vrNumber;
    private BigDecimal supplyPriceExclTax;
    private BigDecimal markupPrct;
    private boolean activeIndicator;
    private Date createdDate;
    private Date lastUpdated;
    private String grNumber;

   public ProductPriceHistory() {
   }

	
   public ProductPriceHistory(Outlet outlet, User userByCreatedBy, User userByUpdatedBy, Company company, SalesTax salesTax, int productId, String productUuid, BigDecimal supplyPriceExclTax, BigDecimal markupPrct, boolean activeIndicator, Date createdDate, Date lastUpdated) {
       this.outlet = outlet;
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.company = company;
       this.salesTax = salesTax;
       this.productId = productId;
       this.productUuid = productUuid;
       this.supplyPriceExclTax = supplyPriceExclTax;
       this.markupPrct = markupPrct;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
   }
   public ProductPriceHistory(Outlet outlet, User userByCreatedBy, User userByUpdatedBy, Company company, SalesTax salesTax, int productId, String productUuid, Integer productVariantId, String productVariantUuid, String coCode, String sroNumber, String hsCode, String description, BigDecimal dollarRate, BigDecimal DUnitValueDeclared, BigDecimal DUnitValueAssessed, BigDecimal DTotalValueDeclared, BigDecimal DTotalValueAssessed, BigDecimal PCustomValueDeclared, BigDecimal PCustomValueAssessed, BigDecimal numberOfUnits, BigDecimal customDutyPrct, BigDecimal customDutyValue, BigDecimal salesTaxPrct, BigDecimal salesTaxValue, BigDecimal regularityDutyPrct, BigDecimal regularityDutyValue, BigDecimal additionalCustomDutyPrct, BigDecimal additionalCustomDutyValue, BigDecimal additionalSalesTaxPrct, BigDecimal additionalSalesTaxValue, BigDecimal excisePrct, BigDecimal exciseValue, BigDecimal totalValue, BigDecimal itPrct, BigDecimal itValue, BigDecimal ftaPrct, BigDecimal ftaValue, String remarks, Integer vrNumber, BigDecimal supplyPriceExclTax, BigDecimal markupPrct, boolean activeIndicator, Date createdDate, Date lastUpdated, String grNumber) {
      this.outlet = outlet;
      this.userByCreatedBy = userByCreatedBy;
      this.userByUpdatedBy = userByUpdatedBy;
      this.company = company;
      this.salesTax = salesTax;
      this.productId = productId;
      this.productUuid = productUuid;
      this.productVariantId = productVariantId;
      this.productVariantUuid = productVariantUuid;
      this.coCode = coCode;
      this.sroNumber = sroNumber;
      this.hsCode = hsCode;
      this.description = description;
      this.dollarRate = dollarRate;
      this.DUnitValueDeclared = DUnitValueDeclared;
      this.DUnitValueAssessed = DUnitValueAssessed;
      this.DTotalValueDeclared = DTotalValueDeclared;
      this.DTotalValueAssessed = DTotalValueAssessed;
      this.PCustomValueDeclared = PCustomValueDeclared;
      this.PCustomValueAssessed = PCustomValueAssessed;
      this.numberOfUnits = numberOfUnits;
      this.customDutyPrct = customDutyPrct;
      this.customDutyValue = customDutyValue;
      this.salesTaxPrct = salesTaxPrct;
      this.salesTaxValue = salesTaxValue;
      this.regularityDutyPrct = regularityDutyPrct;
      this.regularityDutyValue = regularityDutyValue;
      this.additionalCustomDutyPrct = additionalCustomDutyPrct;
      this.additionalCustomDutyValue = additionalCustomDutyValue;
      this.additionalSalesTaxPrct = additionalSalesTaxPrct;
      this.additionalSalesTaxValue = additionalSalesTaxValue;
      this.excisePrct = excisePrct;
      this.exciseValue = exciseValue;
      this.totalValue = totalValue;
      this.itPrct = itPrct;
      this.itValue = itValue;
      this.ftaPrct = ftaPrct;
      this.ftaValue = ftaValue;
      this.remarks = remarks;
      this.vrNumber = vrNumber;
      this.supplyPriceExclTax = supplyPriceExclTax;
      this.markupPrct = markupPrct;
      this.activeIndicator = activeIndicator;
      this.createdDate = createdDate;
      this.lastUpdated = lastUpdated;
      this.grNumber = grNumber;
   }
  
    @Id @GeneratedValue(strategy=IDENTITY)

   
   @Column(name="PRODUCT_PRICE_HISTORY_ID", unique=true, nullable=false)
   public Integer getProductPriceHistoryId() {
       return this.productPriceHistoryId;
   }
   
   public void setProductPriceHistoryId(Integer productPriceHistoryId) {
       this.productPriceHistoryId = productPriceHistoryId;
   }

@ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="OUTLET_ASSOCICATION_ID", nullable=false)
   public Outlet getOutlet() {
       return this.outlet;
   }
   
   public void setOutlet(Outlet outlet) {
       this.outlet = outlet;
   }

@ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="CREATED_BY", nullable=false)
   public User getUserByCreatedBy() {
       return this.userByCreatedBy;
   }
   
   public void setUserByCreatedBy(User userByCreatedBy) {
       this.userByCreatedBy = userByCreatedBy;
   }

@ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="UPDATED_BY", nullable=false)
   public User getUserByUpdatedBy() {
       return this.userByUpdatedBy;
   }
   
   public void setUserByUpdatedBy(User userByUpdatedBy) {
       this.userByUpdatedBy = userByUpdatedBy;
   }

@ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="COMPANY_ASSOCIATION_ID", nullable=false)
   public Company getCompany() {
       return this.company;
   }
   
   public void setCompany(Company company) {
       this.company = company;
   }

@ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="SALES_TAX_ASSOCICATION_ID", nullable=false)
   public SalesTax getSalesTax() {
       return this.salesTax;
   }
   
   public void setSalesTax(SalesTax salesTax) {
       this.salesTax = salesTax;
   }

   
   @Column(name="PRODUCT_ID", nullable=false)
   public int getProductId() {
       return this.productId;
   }
   
   public void setProductId(int productId) {
       this.productId = productId;
   }

   
   @Column(name="PRODUCT_UUID", nullable=false, length=500)
   public String getProductUuid() {
       return this.productUuid;
   }
   
   public void setProductUuid(String productUuid) {
       this.productUuid = productUuid;
   }

   
   @Column(name="PRODUCT_VARIANT_ID")
   public Integer getProductVariantId() {
       return this.productVariantId;
   }
   
   public void setProductVariantId(Integer productVariantId) {
       this.productVariantId = productVariantId;
   }

   
   @Column(name="PRODUCT_VARIANT_UUID", length=500)
   public String getProductVariantUuid() {
       return this.productVariantUuid;
   }
   
   public void setProductVariantUuid(String productVariantUuid) {
       this.productVariantUuid = productVariantUuid;
   }

   
   @Column(name="CO_CODE", length=250)
   public String getCoCode() {
       return this.coCode;
   }
   
   public void setCoCode(String coCode) {
       this.coCode = coCode;
   }

   
   @Column(name="SRO_NUMBER", length=250)
   public String getSroNumber() {
       return this.sroNumber;
   }
   
   public void setSroNumber(String sroNumber) {
       this.sroNumber = sroNumber;
   }

   
   @Column(name="HS_CODE", length=250)
   public String getHsCode() {
       return this.hsCode;
   }
   
   public void setHsCode(String hsCode) {
       this.hsCode = hsCode;
   }

   
   @Column(name="DESCRIPTION", length=1000)
   public String getDescription() {
       return this.description;
   }
   
   public void setDescription(String description) {
       this.description = description;
   }

   
   @Column(name="DOLLAR_RATE", precision=8, scale=5)
   public BigDecimal getDollarRate() {
       return this.dollarRate;
   }
   
   public void setDollarRate(BigDecimal dollarRate) {
       this.dollarRate = dollarRate;
   }

   
   @Column(name="D_UNIT_VALUE_DECLARED", precision=15, scale=5)
   public BigDecimal getDUnitValueDeclared() {
       return this.DUnitValueDeclared;
   }
   
   public void setDUnitValueDeclared(BigDecimal DUnitValueDeclared) {
       this.DUnitValueDeclared = DUnitValueDeclared;
   }

   
   @Column(name="D_UNIT_VALUE_ASSESSED", precision=15, scale=5)
   public BigDecimal getDUnitValueAssessed() {
       return this.DUnitValueAssessed;
   }
   
   public void setDUnitValueAssessed(BigDecimal DUnitValueAssessed) {
       this.DUnitValueAssessed = DUnitValueAssessed;
   }

   
   @Column(name="D_TOTAL_VALUE_DECLARED", precision=20, scale=5)
   public BigDecimal getDTotalValueDeclared() {
       return this.DTotalValueDeclared;
   }
   
   public void setDTotalValueDeclared(BigDecimal DTotalValueDeclared) {
       this.DTotalValueDeclared = DTotalValueDeclared;
   }

   
   @Column(name="D_TOTAL_VALUE_ASSESSED", precision=20, scale=5)
   public BigDecimal getDTotalValueAssessed() {
       return this.DTotalValueAssessed;
   }
   
   public void setDTotalValueAssessed(BigDecimal DTotalValueAssessed) {
       this.DTotalValueAssessed = DTotalValueAssessed;
   }

   
   @Column(name="P_CUSTOM_VALUE_DECLARED", precision=30, scale=5)
   public BigDecimal getPCustomValueDeclared() {
       return this.PCustomValueDeclared;
   }
   
   public void setPCustomValueDeclared(BigDecimal PCustomValueDeclared) {
       this.PCustomValueDeclared = PCustomValueDeclared;
   }

   
   @Column(name="P_CUSTOM_VALUE_ASSESSED", precision=30, scale=5)
   public BigDecimal getPCustomValueAssessed() {
       return this.PCustomValueAssessed;
   }
   
   public void setPCustomValueAssessed(BigDecimal PCustomValueAssessed) {
       this.PCustomValueAssessed = PCustomValueAssessed;
   }

   
   @Column(name="NUMBER_OF_UNITS", precision=15, scale=5)
   public BigDecimal getNumberOfUnits() {
       return this.numberOfUnits;
   }
   
   public void setNumberOfUnits(BigDecimal numberOfUnits) {
       this.numberOfUnits = numberOfUnits;
   }

   
   @Column(name="CUSTOM_DUTY_PRCT", precision=15, scale=5)
   public BigDecimal getCustomDutyPrct() {
       return this.customDutyPrct;
   }
   
   public void setCustomDutyPrct(BigDecimal customDutyPrct) {
       this.customDutyPrct = customDutyPrct;
   }

   
   @Column(name="CUSTOM_DUTY_VALUE", precision=15, scale=5)
   public BigDecimal getCustomDutyValue() {
       return this.customDutyValue;
   }
   
   public void setCustomDutyValue(BigDecimal customDutyValue) {
       this.customDutyValue = customDutyValue;
   }

   
   @Column(name="SALES_TAX_PRCT", precision=15, scale=5)
   public BigDecimal getSalesTaxPrct() {
       return this.salesTaxPrct;
   }
   
   public void setSalesTaxPrct(BigDecimal salesTaxPrct) {
       this.salesTaxPrct = salesTaxPrct;
   }

   
   @Column(name="SALES_TAX_VALUE", precision=15, scale=5)
   public BigDecimal getSalesTaxValue() {
       return this.salesTaxValue;
   }
   
   public void setSalesTaxValue(BigDecimal salesTaxValue) {
       this.salesTaxValue = salesTaxValue;
   }

   
   @Column(name="REGULARITY_DUTY_PRCT", precision=15, scale=5)
   public BigDecimal getRegularityDutyPrct() {
       return this.regularityDutyPrct;
   }
   
   public void setRegularityDutyPrct(BigDecimal regularityDutyPrct) {
       this.regularityDutyPrct = regularityDutyPrct;
   }

   
   @Column(name="REGULARITY_DUTY_VALUE", precision=15, scale=5)
   public BigDecimal getRegularityDutyValue() {
       return this.regularityDutyValue;
   }
   
   public void setRegularityDutyValue(BigDecimal regularityDutyValue) {
       this.regularityDutyValue = regularityDutyValue;
   }

   
   @Column(name="ADDITIONAL_CUSTOM_DUTY_PRCT", precision=15, scale=5)
   public BigDecimal getAdditionalCustomDutyPrct() {
       return this.additionalCustomDutyPrct;
   }
   
   public void setAdditionalCustomDutyPrct(BigDecimal additionalCustomDutyPrct) {
       this.additionalCustomDutyPrct = additionalCustomDutyPrct;
   }

   
   @Column(name="ADDITIONAL_CUSTOM_DUTY_VALUE", precision=15, scale=5)
   public BigDecimal getAdditionalCustomDutyValue() {
       return this.additionalCustomDutyValue;
   }
   
   public void setAdditionalCustomDutyValue(BigDecimal additionalCustomDutyValue) {
       this.additionalCustomDutyValue = additionalCustomDutyValue;
   }

   
   @Column(name="ADDITIONAL_SALES_TAX_PRCT", precision=15, scale=5)
   public BigDecimal getAdditionalSalesTaxPrct() {
       return this.additionalSalesTaxPrct;
   }
   
   public void setAdditionalSalesTaxPrct(BigDecimal additionalSalesTaxPrct) {
       this.additionalSalesTaxPrct = additionalSalesTaxPrct;
   }

   
   @Column(name="ADDITIONAL_SALES_TAX_VALUE", precision=15, scale=5)
   public BigDecimal getAdditionalSalesTaxValue() {
       return this.additionalSalesTaxValue;
   }
   
   public void setAdditionalSalesTaxValue(BigDecimal additionalSalesTaxValue) {
       this.additionalSalesTaxValue = additionalSalesTaxValue;
   }

   
   @Column(name="EXCISE_PRCT", precision=15, scale=5)
   public BigDecimal getExcisePrct() {
       return this.excisePrct;
   }
   
   public void setExcisePrct(BigDecimal excisePrct) {
       this.excisePrct = excisePrct;
   }

   
   @Column(name="EXCISE_VALUE", precision=15, scale=5)
   public BigDecimal getExciseValue() {
       return this.exciseValue;
   }
   
   public void setExciseValue(BigDecimal exciseValue) {
       this.exciseValue = exciseValue;
   }

   
   @Column(name="TOTAL_VALUE", precision=30, scale=5)
   public BigDecimal getTotalValue() {
       return this.totalValue;
   }
   
   public void setTotalValue(BigDecimal totalValue) {
       this.totalValue = totalValue;
   }

   
   @Column(name="IT_PRCT", precision=15, scale=5)
   public BigDecimal getItPrct() {
       return this.itPrct;
   }
   
   public void setItPrct(BigDecimal itPrct) {
       this.itPrct = itPrct;
   }

   
   @Column(name="IT_VALUE", precision=15, scale=5)
   public BigDecimal getItValue() {
       return this.itValue;
   }
   
   public void setItValue(BigDecimal itValue) {
       this.itValue = itValue;
   }

   
   @Column(name="FTA_PRCT", precision=15, scale=5)
   public BigDecimal getFtaPrct() {
       return this.ftaPrct;
   }
   
   public void setFtaPrct(BigDecimal ftaPrct) {
       this.ftaPrct = ftaPrct;
   }

   
   @Column(name="FTA_VALUE", precision=15, scale=5)
   public BigDecimal getFtaValue() {
       return this.ftaValue;
   }
   
   public void setFtaValue(BigDecimal ftaValue) {
       this.ftaValue = ftaValue;
   }

   
   @Column(name="REMARKS", length=1000)
   public String getRemarks() {
       return this.remarks;
   }
   
   public void setRemarks(String remarks) {
       this.remarks = remarks;
   }

   
   @Column(name="VR_NUMBER")
   public Integer getVrNumber() {
       return this.vrNumber;
   }
   
   public void setVrNumber(Integer vrNumber) {
       this.vrNumber = vrNumber;
   }

   
   @Column(name="SUPPLY_PRICE_EXCL_TAX", nullable=false, precision=20)
   public BigDecimal getSupplyPriceExclTax() {
       return this.supplyPriceExclTax;
   }
   
   public void setSupplyPriceExclTax(BigDecimal supplyPriceExclTax) {
       this.supplyPriceExclTax = supplyPriceExclTax;
   }

   
   @Column(name="MARKUP_PRCT", nullable=false, precision=8, scale=5)
   public BigDecimal getMarkupPrct() {
       return this.markupPrct;
   }
   
   public void setMarkupPrct(BigDecimal markupPrct) {
       this.markupPrct = markupPrct;
   }

   
   @Column(name="ACTIVE_INDICATOR", nullable=false)
   public boolean isActiveIndicator() {
       return this.activeIndicator;
   }
   
   public void setActiveIndicator(boolean activeIndicator) {
       this.activeIndicator = activeIndicator;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name="CREATED_DATE", nullable=false, length=19)
   public Date getCreatedDate() {
       return this.createdDate;
   }
   
   public void setCreatedDate(Date createdDate) {
       this.createdDate = createdDate;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name="LAST_UPDATED", nullable=false, length=19)
   public Date getLastUpdated() {
       return this.lastUpdated;
   }
   
   public void setLastUpdated(Date lastUpdated) {
       this.lastUpdated = lastUpdated;
   }

   
   @Column(name="GR_NUMBER", length=500)
   public String getGrNumber() {
       return this.grNumber;
   }
   
   public void setGrNumber(String grNumber) {
       this.grNumber = grNumber;
   }




}


