package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegisterReportId generated by hbm2java
 */
@Embeddable
public class RegisterReportId  implements java.io.Serializable {


    private Integer outletAssocicationId;
    private String outletName;
    private BigDecimal cashAmtActual;
    private BigDecimal creditCardAmtActual;
    private byte[] openingDate;
    private byte[] closingDate;
    private String openBy;
    private byte[] closeBy;
    private String status;
    private int companyAssociationId;
    private int dailyRegisterId;
    private String registerClosingNotes;
    private String registerOpeningNotes;

   public RegisterReportId() {
   }

	
   public RegisterReportId(BigDecimal cashAmtActual, BigDecimal creditCardAmtActual, int companyAssociationId, int dailyRegisterId) {
       this.cashAmtActual = cashAmtActual;
       this.creditCardAmtActual = creditCardAmtActual;
       this.companyAssociationId = companyAssociationId;
       this.dailyRegisterId = dailyRegisterId;
   }
   public RegisterReportId(Integer outletAssocicationId, String outletName, BigDecimal cashAmtActual, BigDecimal creditCardAmtActual, byte[] openingDate, byte[] closingDate, String openBy, byte[] closeBy, String status, int companyAssociationId, int dailyRegisterId, String registerClosingNotes, String registerOpeningNotes) {
      this.outletAssocicationId = outletAssocicationId;
      this.outletName = outletName;
      this.cashAmtActual = cashAmtActual;
      this.creditCardAmtActual = creditCardAmtActual;
      this.openingDate = openingDate;
      this.closingDate = closingDate;
      this.openBy = openBy;
      this.closeBy = closeBy;
      this.status = status;
      this.companyAssociationId = companyAssociationId;
      this.dailyRegisterId = dailyRegisterId;
      this.registerClosingNotes = registerClosingNotes;
      this.registerOpeningNotes = registerOpeningNotes;
   }
  


   @Column(name="OUTLET_ASSOCICATION_ID")
   public Integer getOutletAssocicationId() {
       return this.outletAssocicationId;
   }
   
   public void setOutletAssocicationId(Integer outletAssocicationId) {
       this.outletAssocicationId = outletAssocicationId;
   }


   @Column(name="OUTLET_NAME", length=100)
   public String getOutletName() {
       return this.outletName;
   }
   
   public void setOutletName(String outletName) {
       this.outletName = outletName;
   }


   @Column(name="CASH_AMT_ACTUAL", nullable=false, precision=20)
   public BigDecimal getCashAmtActual() {
       return this.cashAmtActual;
   }
   
   public void setCashAmtActual(BigDecimal cashAmtActual) {
       this.cashAmtActual = cashAmtActual;
   }


   @Column(name="CREDIT_CARD_AMT_ACTUAL", nullable=false, precision=20)
   public BigDecimal getCreditCardAmtActual() {
       return this.creditCardAmtActual;
   }
   
   public void setCreditCardAmtActual(BigDecimal creditCardAmtActual) {
       this.creditCardAmtActual = creditCardAmtActual;
   }


   @Column(name="OPENING_DATE")
   public byte[] getOpeningDate() {
       return this.openingDate;
   }
   
   public void setOpeningDate(byte[] openingDate) {
       this.openingDate = openingDate;
   }


   @Column(name="CLOSING_DATE")
   public byte[] getClosingDate() {
       return this.closingDate;
   }
   
   public void setClosingDate(byte[] closingDate) {
       this.closingDate = closingDate;
   }


   @Column(name="Open_By")
   public String getOpenBy() {
       return this.openBy;
   }
   
   public void setOpenBy(String openBy) {
       this.openBy = openBy;
   }


   @Column(name="Close_By")
   public byte[] getCloseBy() {
       return this.closeBy;
   }
   
   public void setCloseBy(byte[] closeBy) {
       this.closeBy = closeBy;
   }


   @Column(name="Status", length=45)
   public String getStatus() {
       return this.status;
   }
   
   public void setStatus(String status) {
       this.status = status;
   }


   @Column(name="COMPANY_ASSOCIATION_ID", nullable=false)
   public int getCompanyAssociationId() {
       return this.companyAssociationId;
   }
   
   public void setCompanyAssociationId(int companyAssociationId) {
       this.companyAssociationId = companyAssociationId;
   }


   @Column(name="DAILY_REGISTER_ID", nullable=false)
   public int getDailyRegisterId() {
       return this.dailyRegisterId;
   }
   
   public void setDailyRegisterId(int dailyRegisterId) {
       this.dailyRegisterId = dailyRegisterId;
   }


   @Column(name="REGISTER_CLOSING_NOTES", length=256)
   public String getRegisterClosingNotes() {
       return this.registerClosingNotes;
   }
   
   public void setRegisterClosingNotes(String registerClosingNotes) {
       this.registerClosingNotes = registerClosingNotes;
   }


   @Column(name="REGISTER_OPENING_NOTES", length=256)
   public String getRegisterOpeningNotes() {
       return this.registerOpeningNotes;
   }
   
   public void setRegisterOpeningNotes(String registerOpeningNotes) {
       this.registerOpeningNotes = registerOpeningNotes;
   }


  public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegisterReportId) ) return false;
		 RegisterReportId castOther = ( RegisterReportId ) other; 
        
		 return ( (this.getOutletAssocicationId()==castOther.getOutletAssocicationId()) || ( this.getOutletAssocicationId()!=null && castOther.getOutletAssocicationId()!=null && this.getOutletAssocicationId().equals(castOther.getOutletAssocicationId()) ) )
&& ( (this.getOutletName()==castOther.getOutletName()) || ( this.getOutletName()!=null && castOther.getOutletName()!=null && this.getOutletName().equals(castOther.getOutletName()) ) )
&& ( (this.getCashAmtActual()==castOther.getCashAmtActual()) || ( this.getCashAmtActual()!=null && castOther.getCashAmtActual()!=null && this.getCashAmtActual().equals(castOther.getCashAmtActual()) ) )
&& ( (this.getCreditCardAmtActual()==castOther.getCreditCardAmtActual()) || ( this.getCreditCardAmtActual()!=null && castOther.getCreditCardAmtActual()!=null && this.getCreditCardAmtActual().equals(castOther.getCreditCardAmtActual()) ) )
&& ( (this.getOpeningDate()==castOther.getOpeningDate()) || ( this.getOpeningDate()!=null && castOther.getOpeningDate()!=null && Arrays.equals(this.getOpeningDate(), castOther.getOpeningDate()) ) )
&& ( (this.getClosingDate()==castOther.getClosingDate()) || ( this.getClosingDate()!=null && castOther.getClosingDate()!=null && Arrays.equals(this.getClosingDate(), castOther.getClosingDate()) ) )
&& ( (this.getOpenBy()==castOther.getOpenBy()) || ( this.getOpenBy()!=null && castOther.getOpenBy()!=null && this.getOpenBy().equals(castOther.getOpenBy()) ) )
&& ( (this.getCloseBy()==castOther.getCloseBy()) || ( this.getCloseBy()!=null && castOther.getCloseBy()!=null && Arrays.equals(this.getCloseBy(), castOther.getCloseBy()) ) )
&& ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
&& (this.getCompanyAssociationId()==castOther.getCompanyAssociationId())
&& (this.getDailyRegisterId()==castOther.getDailyRegisterId())
&& ( (this.getRegisterClosingNotes()==castOther.getRegisterClosingNotes()) || ( this.getRegisterClosingNotes()!=null && castOther.getRegisterClosingNotes()!=null && this.getRegisterClosingNotes().equals(castOther.getRegisterClosingNotes()) ) )
&& ( (this.getRegisterOpeningNotes()==castOther.getRegisterOpeningNotes()) || ( this.getRegisterOpeningNotes()!=null && castOther.getRegisterOpeningNotes()!=null && this.getRegisterOpeningNotes().equals(castOther.getRegisterOpeningNotes()) ) );
  }
  
  public int hashCode() {
        int result = 17;
        
        result = 37 * result + ( getOutletAssocicationId() == null ? 0 : this.getOutletAssocicationId().hashCode() );
        result = 37 * result + ( getOutletName() == null ? 0 : this.getOutletName().hashCode() );
        result = 37 * result + ( getCashAmtActual() == null ? 0 : this.getCashAmtActual().hashCode() );
        result = 37 * result + ( getCreditCardAmtActual() == null ? 0 : this.getCreditCardAmtActual().hashCode() );
        result = 37 * result + ( getOpeningDate() == null ? 0 : Arrays.hashCode(this.getOpeningDate()) );
        result = 37 * result + ( getClosingDate() == null ? 0 : Arrays.hashCode(this.getClosingDate()) );
        result = 37 * result + ( getOpenBy() == null ? 0 : this.getOpenBy().hashCode() );
        result = 37 * result + ( getCloseBy() == null ? 0 : Arrays.hashCode(this.getCloseBy()) );
        result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
        result = 37 * result + this.getCompanyAssociationId();
        result = 37 * result + this.getDailyRegisterId();
        result = 37 * result + ( getRegisterClosingNotes() == null ? 0 : this.getRegisterClosingNotes().hashCode() );
        result = 37 * result + ( getRegisterOpeningNotes() == null ? 0 : this.getRegisterOpeningNotes().hashCode() );
        return result;
  }   


}


