package com.dowhile;

// Generated Dec 23, 2017 11:31:14 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SmsReport generated by hbm2java
 */
@Entity
@Table(name = "sms_report")
public class SmsReport implements java.io.Serializable {

	private SmsReportId id;

	public SmsReport() {
	}

	public SmsReport(SmsReportId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "messageDetailId", column = @Column(name = "MESSAGE_DETAIL_ID", nullable = false)),
			@AttributeOverride(name = "senderId", column = @Column(name = "SENDER_ID", length = 256)),
			@AttributeOverride(name = "receiverId", column = @Column(name = "RECEIVER_ID", length = 256)),
			@AttributeOverride(name = "messageDescription", column = @Column(name = "MESSAGE_DESCRIPTION", length = 1000)),
			@AttributeOverride(name = "deliveryId", column = @Column(name = "DELIVERY_ID", length = 65535)),
			@AttributeOverride(name = "deliveryStatus", column = @Column(name = "DELIVERY_STATUS", length = 1000)),
			@AttributeOverride(name = "messageAssociationId", column = @Column(name = "MESSAGE_ASSOCIATION_ID", nullable = false)),
			@AttributeOverride(name = "messageBundleCount", column = @Column(name = "MESSAGE_BUNDLE_COUNT")),
			@AttributeOverride(name = "outletAssocicationId", column = @Column(name = "OUTLET_ASSOCICATION_ID")),
			@AttributeOverride(name = "outletName", column = @Column(name = "OUTLET_NAME", length = 100)),
			@AttributeOverride(name = "smsSentDate", column = @Column(name = "SMS_SENT_DATE", length = 49)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE", length = 10)),
			@AttributeOverride(name = "senderName", column = @Column(name = "SENDER_NAME", length = 65535)),
			@AttributeOverride(name = "customerName", column = @Column(name = "CUSTOMER_NAME", length = 200)),
			@AttributeOverride(name = "companyAssociationId", column = @Column(name = "COMPANY_ASSOCIATION_ID", nullable = false)) })
	public SmsReportId getId() {
		return this.id;
	}

	public void setId(SmsReportId id) {
		this.id = id;
	}

}
