package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status"
    ,catalog="ecom"
    , uniqueConstraints = @UniqueConstraint(columnNames="STATUS_CODE") 
)
public class Status  implements java.io.Serializable {


     private Integer statusId;
     private String statusCode;
     private String statusDesc;
     private boolean activeIndicator;
     private Date createdDate;
     private Date lastUpdated;
     private Integer createdBy;
     private Integer updatedBy;
     private Set<Receipt> receipts = new HashSet<Receipt>(0);
     private Set<StockOrder> stockOrders = new HashSet<StockOrder>(0);
     private Set<DailyRegister> dailyRegisters = new HashSet<DailyRegister>(0);
     private Set<InvoiceMain> invoiceMains = new HashSet<InvoiceMain>(0);
     private Set<OrderMain> orderMains = new HashSet<OrderMain>(0);
     private Set<InventoryCount> inventoryCounts = new HashSet<InventoryCount>(0);

    public Status() {
    }

	
    public Status(String statusCode, boolean activeIndicator, Date createdDate, Date lastUpdated) {
        this.statusCode = statusCode;
        this.activeIndicator = activeIndicator;
        this.createdDate = createdDate;
        this.lastUpdated = lastUpdated;
    }
    public Status(String statusCode, String statusDesc, boolean activeIndicator, Date createdDate, Date lastUpdated, Integer createdBy, Integer updatedBy, Set<Receipt> receipts, Set<StockOrder> stockOrders, Set<DailyRegister> dailyRegisters, Set<InvoiceMain> invoiceMains, Set<OrderMain> orderMains, Set<InventoryCount> inventoryCounts) {
       this.statusCode = statusCode;
       this.statusDesc = statusDesc;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.receipts = receipts;
       this.stockOrders = stockOrders;
       this.dailyRegisters = dailyRegisters;
       this.invoiceMains = invoiceMains;
       this.orderMains = orderMains;
       this.inventoryCounts = inventoryCounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STATUS_ID", unique=true, nullable=false)
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="STATUS_CODE", unique=true, nullable=false, length=5)
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="STATUS_DESC", length=45)
    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    
    @Column(name="ACTIVE_INDICATOR", nullable=false)
    public boolean isActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(boolean activeIndicator) {
        this.activeIndicator = activeIndicator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Receipt> getReceipts() {
        return this.receipts;
    }
    
    public void setReceipts(Set<Receipt> receipts) {
        this.receipts = receipts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<StockOrder> getStockOrders() {
        return this.stockOrders;
    }
    
    public void setStockOrders(Set<StockOrder> stockOrders) {
        this.stockOrders = stockOrders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<DailyRegister> getDailyRegisters() {
        return this.dailyRegisters;
    }
    
    public void setDailyRegisters(Set<DailyRegister> dailyRegisters) {
        this.dailyRegisters = dailyRegisters;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<InvoiceMain> getInvoiceMains() {
        return this.invoiceMains;
    }
    
    public void setInvoiceMains(Set<InvoiceMain> invoiceMains) {
        this.invoiceMains = invoiceMains;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<OrderMain> getOrderMains() {
        return this.orderMains;
    }
    
    public void setOrderMains(Set<OrderMain> orderMains) {
        this.orderMains = orderMains;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<InventoryCount> getInventoryCounts() {
        return this.inventoryCounts;
    }
    
    public void setInventoryCounts(Set<InventoryCount> inventoryCounts) {
        this.inventoryCounts = inventoryCounts;
    }




}


