package com.dowhile;
// Generated Apr 24, 2019 7:32:29 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StockOrderV generated by hbm2java
 */
@Entity
@Table(name="stock_order_v"
    ,catalog="ecom"
)
public class StockOrderV  implements java.io.Serializable {


     private StockOrderVId id;

    public StockOrderV() {
    }

    public StockOrderV(StockOrderVId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stockOrderId", column=@Column(name="STOCK_ORDER_ID", nullable=false) ), 
        @AttributeOverride(name="stockRefNo", column=@Column(name="STOCK_REF_NO", length=45) ), 
        @AttributeOverride(name="statusAssocicationId", column=@Column(name="STATUS_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="diliveryDueDate", column=@Column(name="DILIVERY_DUE_DATE", nullable=false, length=10) ), 
        @AttributeOverride(name="contactId", column=@Column(name="CONTACT_ID", nullable=false) ), 
        @AttributeOverride(name="orderNo", column=@Column(name="ORDER_NO", length=45) ), 
        @AttributeOverride(name="outletAssocicationId", column=@Column(name="OUTLET_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="sourceOutletAssocicationId", column=@Column(name="SOURCE_OUTLET_ASSOCICATION_ID") ), 
        @AttributeOverride(name="contactInvoiceNo", column=@Column(name="CONTACT_INVOICE_NO", length=45) ), 
        @AttributeOverride(name="stockOrderDate", column=@Column(name="STOCK_ORDER_DATE", length=19) ), 
        @AttributeOverride(name="remarks", column=@Column(name="REMARKS", length=500) ), 
        @AttributeOverride(name="ordrRecvDate", column=@Column(name="ORDR_RECV_DATE", length=19) ), 
        @AttributeOverride(name="returnNo", column=@Column(name="RETURN_NO", length=45) ), 
        @AttributeOverride(name="stockOrderTypeAssocicationId", column=@Column(name="STOCK_ORDER_TYPE_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="autofillReorder", column=@Column(name="AUTOFILL_REORDER", nullable=false) ), 
        @AttributeOverride(name="retailPriceBill", column=@Column(name="RETAIL_PRICE_BILL", nullable=false) ), 
        @AttributeOverride(name="activeIndicator", column=@Column(name="ACTIVE_INDICATOR", nullable=false) ), 
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE", nullable=false, length=19) ), 
        @AttributeOverride(name="lastUpdated", column=@Column(name="LAST_UPDATED", nullable=false, length=19) ), 
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY") ), 
        @AttributeOverride(name="updatedBy", column=@Column(name="UPDATED_BY") ), 
        @AttributeOverride(name="companyAssociationId", column=@Column(name="COMPANY_ASSOCIATION_ID", nullable=false) ), 
        @AttributeOverride(name="totalItems", column=@Column(name="TOTAL_ITEMS", nullable=false, precision=20) ), 
        @AttributeOverride(name="totalAmount", column=@Column(name="TOTAL_AMOUNT", nullable=false, precision=20) ), 
        @AttributeOverride(name="statusDesc", column=@Column(name="STATUS_DESC", length=45) ), 
        @AttributeOverride(name="stockOrderTypeDesc", column=@Column(name="STOCK_ORDER_TYPE_DESC", length=45) ), 
        @AttributeOverride(name="outlet", column=@Column(name="outlet", length=100) ), 
        @AttributeOverride(name="source", column=@Column(name="source", length=100) ), 
        @AttributeOverride(name="supplier", column=@Column(name="Supplier", length=200) ) } )
    public StockOrderVId getId() {
        return this.id;
    }
    
    public void setId(StockOrderVId id) {
        this.id = id;
    }




}


