package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TempSaleId generated by hbm2java
 */
@Embeddable
public class TempSaleId  implements java.io.Serializable {


     private String product;
     private String outlet;
     private Date createdDate;
     private BigDecimal revenue;
     private BigDecimal revenueTaxIncl;
     private BigDecimal costOfGoods;
     private BigDecimal grossProfit;
     private BigDecimal margin;
     private BigDecimal itemsSold;
     private BigDecimal tax;
     private int companyAssociationId;
     private Integer outletAssocicationId;

    public TempSaleId() {
    }

	
    public TempSaleId(int companyAssociationId) {
        this.companyAssociationId = companyAssociationId;
    }
    public TempSaleId(String product, String outlet, Date createdDate, BigDecimal revenue, BigDecimal revenueTaxIncl, BigDecimal costOfGoods, BigDecimal grossProfit, BigDecimal margin, BigDecimal itemsSold, BigDecimal tax, int companyAssociationId, Integer outletAssocicationId) {
       this.product = product;
       this.outlet = outlet;
       this.createdDate = createdDate;
       this.revenue = revenue;
       this.revenueTaxIncl = revenueTaxIncl;
       this.costOfGoods = costOfGoods;
       this.grossProfit = grossProfit;
       this.margin = margin;
       this.itemsSold = itemsSold;
       this.tax = tax;
       this.companyAssociationId = companyAssociationId;
       this.outletAssocicationId = outletAssocicationId;
    }
   


    @Column(name="Product", length=500)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }


    @Column(name="Outlet", length=100)
    public String getOutlet() {
        return this.outlet;
    }
    
    public void setOutlet(String outlet) {
        this.outlet = outlet;
    }


    @Column(name="CREATED_DATE", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="Revenue", precision=52)
    public BigDecimal getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }


    @Column(name="Revenue_tax_incl", precision=53)
    public BigDecimal getRevenueTaxIncl() {
        return this.revenueTaxIncl;
    }
    
    public void setRevenueTaxIncl(BigDecimal revenueTaxIncl) {
        this.revenueTaxIncl = revenueTaxIncl;
    }


    @Column(name="Cost_of_Goods", precision=52)
    public BigDecimal getCostOfGoods() {
        return this.costOfGoods;
    }
    
    public void setCostOfGoods(BigDecimal costOfGoods) {
        this.costOfGoods = costOfGoods;
    }


    @Column(name="Gross_Profit", precision=53)
    public BigDecimal getGrossProfit() {
        return this.grossProfit;
    }
    
    public void setGrossProfit(BigDecimal grossProfit) {
        this.grossProfit = grossProfit;
    }


    @Column(name="Margin", precision=52, scale=6)
    public BigDecimal getMargin() {
        return this.margin;
    }
    
    public void setMargin(BigDecimal margin) {
        this.margin = margin;
    }


    @Column(name="Items_Sold", precision=32, scale=0)
    public BigDecimal getItemsSold() {
        return this.itemsSold;
    }
    
    public void setItemsSold(BigDecimal itemsSold) {
        this.itemsSold = itemsSold;
    }


    @Column(name="Tax", precision=42)
    public BigDecimal getTax() {
        return this.tax;
    }
    
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }


    @Column(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public int getCompanyAssociationId() {
        return this.companyAssociationId;
    }
    
    public void setCompanyAssociationId(int companyAssociationId) {
        this.companyAssociationId = companyAssociationId;
    }


    @Column(name="OUTLET_ASSOCICATION_ID")
    public Integer getOutletAssocicationId() {
        return this.outletAssocicationId;
    }
    
    public void setOutletAssocicationId(Integer outletAssocicationId) {
        this.outletAssocicationId = outletAssocicationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TempSaleId) ) return false;
		 TempSaleId castOther = ( TempSaleId ) other; 
         
		 return ( (this.getProduct()==castOther.getProduct()) || ( this.getProduct()!=null && castOther.getProduct()!=null && this.getProduct().equals(castOther.getProduct()) ) )
 && ( (this.getOutlet()==castOther.getOutlet()) || ( this.getOutlet()!=null && castOther.getOutlet()!=null && this.getOutlet().equals(castOther.getOutlet()) ) )
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && this.getCreatedDate().equals(castOther.getCreatedDate()) ) )
 && ( (this.getRevenue()==castOther.getRevenue()) || ( this.getRevenue()!=null && castOther.getRevenue()!=null && this.getRevenue().equals(castOther.getRevenue()) ) )
 && ( (this.getRevenueTaxIncl()==castOther.getRevenueTaxIncl()) || ( this.getRevenueTaxIncl()!=null && castOther.getRevenueTaxIncl()!=null && this.getRevenueTaxIncl().equals(castOther.getRevenueTaxIncl()) ) )
 && ( (this.getCostOfGoods()==castOther.getCostOfGoods()) || ( this.getCostOfGoods()!=null && castOther.getCostOfGoods()!=null && this.getCostOfGoods().equals(castOther.getCostOfGoods()) ) )
 && ( (this.getGrossProfit()==castOther.getGrossProfit()) || ( this.getGrossProfit()!=null && castOther.getGrossProfit()!=null && this.getGrossProfit().equals(castOther.getGrossProfit()) ) )
 && ( (this.getMargin()==castOther.getMargin()) || ( this.getMargin()!=null && castOther.getMargin()!=null && this.getMargin().equals(castOther.getMargin()) ) )
 && ( (this.getItemsSold()==castOther.getItemsSold()) || ( this.getItemsSold()!=null && castOther.getItemsSold()!=null && this.getItemsSold().equals(castOther.getItemsSold()) ) )
 && ( (this.getTax()==castOther.getTax()) || ( this.getTax()!=null && castOther.getTax()!=null && this.getTax().equals(castOther.getTax()) ) )
 && (this.getCompanyAssociationId()==castOther.getCompanyAssociationId())
 && ( (this.getOutletAssocicationId()==castOther.getOutletAssocicationId()) || ( this.getOutletAssocicationId()!=null && castOther.getOutletAssocicationId()!=null && this.getOutletAssocicationId().equals(castOther.getOutletAssocicationId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProduct() == null ? 0 : this.getProduct().hashCode() );
         result = 37 * result + ( getOutlet() == null ? 0 : this.getOutlet().hashCode() );
         result = 37 * result + ( getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode() );
         result = 37 * result + ( getRevenue() == null ? 0 : this.getRevenue().hashCode() );
         result = 37 * result + ( getRevenueTaxIncl() == null ? 0 : this.getRevenueTaxIncl().hashCode() );
         result = 37 * result + ( getCostOfGoods() == null ? 0 : this.getCostOfGoods().hashCode() );
         result = 37 * result + ( getGrossProfit() == null ? 0 : this.getGrossProfit().hashCode() );
         result = 37 * result + ( getMargin() == null ? 0 : this.getMargin().hashCode() );
         result = 37 * result + ( getItemsSold() == null ? 0 : this.getItemsSold().hashCode() );
         result = 37 * result + ( getTax() == null ? 0 : this.getTax().hashCode() );
         result = 37 * result + this.getCompanyAssociationId();
         result = 37 * result + ( getOutletAssocicationId() == null ? 0 : this.getOutletAssocicationId().hashCode() );
         return result;
   }   


}


