package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VariantAttributeValues generated by hbm2java
 */
@Entity
@Table(name="variant_attribute_values"
    ,catalog="ecom"
)
public class VariantAttributeValues  implements java.io.Serializable {


     private Integer variantAttributeValuesId;
     private ProductVariant productVariant;
     private User userByCreatedBy;
     private User userByUpdatedBy;
     private Company company;
     private VariantAttribute variantAttribute;
     private Product product;
     private String attributeValue;
     private String productUuid;
     private boolean activeIndicator;
     private Date createdDate;
     private Date lastUpdated;

    public VariantAttributeValues() {
    }

    public VariantAttributeValues(ProductVariant productVariant, User userByCreatedBy, User userByUpdatedBy, Company company, VariantAttribute variantAttribute, Product product, String attributeValue, String productUuid, boolean activeIndicator, Date createdDate, Date lastUpdated) {
       this.productVariant = productVariant;
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.company = company;
       this.variantAttribute = variantAttribute;
       this.product = product;
       this.attributeValue = attributeValue;
       this.productUuid = productUuid;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VARIANT_ATTRIBUTE_VALUES_ID", unique=true, nullable=false)
    public Integer getVariantAttributeValuesId() {
        return this.variantAttributeValuesId;
    }
    
    public void setVariantAttributeValuesId(Integer variantAttributeValuesId) {
        this.variantAttributeValuesId = variantAttributeValuesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_VARIANT_ASSOCICATION_ID", nullable=false)
    public ProductVariant getProductVariant() {
        return this.productVariant;
    }
    
    public void setProductVariant(ProductVariant productVariant) {
        this.productVariant = productVariant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATED_BY", nullable=false)
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UPDATED_BY", nullable=false)
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VARIANT_ATTRIBUTE_ASSOCICATION_ID", nullable=false)
    public VariantAttribute getVariantAttribute() {
        return this.variantAttribute;
    }
    
    public void setVariantAttribute(VariantAttribute variantAttribute) {
        this.variantAttribute = variantAttribute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ASSOCIATION_ID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="ATTRIBUTE_VALUE", nullable=false, length=200)
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }

    
    @Column(name="PRODUCT_UUID", nullable=false, length=500)
    public String getProductUuid() {
        return this.productUuid;
    }
    
    public void setProductUuid(String productUuid) {
        this.productUuid = productUuid;
    }

    
    @Column(name="ACTIVE_INDICATOR", nullable=false)
    public boolean isActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(boolean activeIndicator) {
        this.activeIndicator = activeIndicator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


