package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Announcement generated by hbm2java
 */
@Entity
@Table(name="announcement"
    ,catalog="ecom"
)
public class Announcement  implements java.io.Serializable {


     private Integer announcementId;
     private User userByCreatedBy;
     private User userByUpdatedBy;
     private Company company;
     private String description;
     private byte[] announcementDetail;
     private Date announcementDate;
     private Date createdDate;
     private Date lastUpdated;

    public Announcement() {
    }

    public Announcement(User userByCreatedBy, User userByUpdatedBy, Company company, String description, byte[] announcementDetail, Date announcementDate, Date createdDate, Date lastUpdated) {
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.company = company;
       this.description = description;
       this.announcementDetail = announcementDetail;
       this.announcementDate = announcementDate;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ANNOUNCEMENT_ID", unique=true, nullable=false)
    public Integer getAnnouncementId() {
        return this.announcementId;
    }
    
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATED_BY", nullable=false)
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UPDATED_BY", nullable=false)
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ANNOUNCEMENT_DETAIL", nullable=false)
    public byte[] getAnnouncementDetail() {
        return this.announcementDetail;
    }
    
    public void setAnnouncementDetail(byte[] announcementDetail) {
        this.announcementDetail = announcementDetail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ANNOUNCEMENT_DATE", nullable=false, length=10)
    public Date getAnnouncementDate() {
        return this.announcementDate;
    }
    
    public void setAnnouncementDate(Date announcementDate) {
        this.announcementDate = announcementDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


