package com.dowhile;
// Generated Jan 22, 2018 1:38:57 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InventoryDetailReport generated by hbm2java
 */
@Entity
@Table(name="inventory__detail_report"
    ,catalog="ecom"
)
public class InventoryDetailReport  implements java.io.Serializable {


     private InventoryDetailReportId id;

    public InventoryDetailReport() {
    }

    public InventoryDetailReport(InventoryDetailReportId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="productName", column=@Column(name="PRODUCT_NAME", length=65535) ), 
        @AttributeOverride(name="sku", column=@Column(name="SKU", nullable=false, length=500) ), 
        @AttributeOverride(name="supplyPriceExclTax", column=@Column(name="SUPPLY_PRICE_EXCL_TAX", nullable=false, precision=20) ), 
        @AttributeOverride(name="markupPrct", column=@Column(name="MARKUP_PRCT", nullable=false, precision=8, scale=5) ), 
        @AttributeOverride(name="reorderPoint", column=@Column(name="REORDER_POINT") ), 
        @AttributeOverride(name="reorderAmount", column=@Column(name="REORDER_AMOUNT", precision=20) ), 
        @AttributeOverride(name="currentInventory", column=@Column(name="CURRENT_INVENTORY") ), 
        @AttributeOverride(name="netPrice", column=@Column(name="NET_PRICE", precision=33, scale=11) ), 
        @AttributeOverride(name="outletName", column=@Column(name="OUTLET_NAME", length=100) ), 
        @AttributeOverride(name="outletAssocicationId", column=@Column(name="OUTLET_ASSOCICATION_ID", nullable=false) ), 
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE", nullable=false, length=19) ), 
        @AttributeOverride(name="brandName", column=@Column(name="BRAND_NAME", length=200) ), 
        @AttributeOverride(name="productType", column=@Column(name="PRODUCT_TYPE", length=200) ), 
        @AttributeOverride(name="contactName", column=@Column(name="CONTACT_NAME", length=200) ), 
        @AttributeOverride(name="companyAssociationId", column=@Column(name="COMPANY_ASSOCIATION_ID", nullable=false) ), 
        @AttributeOverride(name="stockValue", column=@Column(name="STOCK_VALUE", precision=30) ), 
        @AttributeOverride(name="retailValue", column=@Column(name="RETAIL_VALUE", precision=43, scale=11) ), 
        @AttributeOverride(name="totalStockSent", column=@Column(name="TOTAL_STOCK_SENT", precision=32, scale=0) ) } )
    public InventoryDetailReportId getId() {
        return this.id;
    }
    
    public void setId(InventoryDetailReportId id) {
        this.id = id;
    }




}


