package com.dowhile;
// Generated Jan 22, 2018 1:38:57 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InventoryDetailReportId generated by hbm2java
 */
@Embeddable
public class InventoryDetailReportId  implements java.io.Serializable {


     private int id;
     private String productName;
     private String sku;
     private BigDecimal supplyPriceExclTax;
     private BigDecimal markupPrct;
     private Integer reorderPoint;
     private BigDecimal reorderAmount;
     private Integer currentInventory;
     private BigDecimal netPrice;
     private String outletName;
     private int outletAssocicationId;
     private Date createdDate;
     private String brandName;
     private String productType;
     private String contactName;
     private int companyAssociationId;
     private BigDecimal stockValue;
     private BigDecimal retailValue;
     private BigDecimal totalStockSent;

    public InventoryDetailReportId() {
    }

	
    public InventoryDetailReportId(int id, String sku, BigDecimal supplyPriceExclTax, BigDecimal markupPrct, int outletAssocicationId, Date createdDate, int companyAssociationId) {
        this.id = id;
        this.sku = sku;
        this.supplyPriceExclTax = supplyPriceExclTax;
        this.markupPrct = markupPrct;
        this.outletAssocicationId = outletAssocicationId;
        this.createdDate = createdDate;
        this.companyAssociationId = companyAssociationId;
    }
    public InventoryDetailReportId(int id, String productName, String sku, BigDecimal supplyPriceExclTax, BigDecimal markupPrct, Integer reorderPoint, BigDecimal reorderAmount, Integer currentInventory, BigDecimal netPrice, String outletName, int outletAssocicationId, Date createdDate, String brandName, String productType, String contactName, int companyAssociationId, BigDecimal stockValue, BigDecimal retailValue, BigDecimal totalStockSent) {
       this.id = id;
       this.productName = productName;
       this.sku = sku;
       this.supplyPriceExclTax = supplyPriceExclTax;
       this.markupPrct = markupPrct;
       this.reorderPoint = reorderPoint;
       this.reorderAmount = reorderAmount;
       this.currentInventory = currentInventory;
       this.netPrice = netPrice;
       this.outletName = outletName;
       this.outletAssocicationId = outletAssocicationId;
       this.createdDate = createdDate;
       this.brandName = brandName;
       this.productType = productType;
       this.contactName = contactName;
       this.companyAssociationId = companyAssociationId;
       this.stockValue = stockValue;
       this.retailValue = retailValue;
       this.totalStockSent = totalStockSent;
    }
   


    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="PRODUCT_NAME", length=65535)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }


    @Column(name="SKU", nullable=false, length=500)
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }


    @Column(name="SUPPLY_PRICE_EXCL_TAX", nullable=false, precision=20)
    public BigDecimal getSupplyPriceExclTax() {
        return this.supplyPriceExclTax;
    }
    
    public void setSupplyPriceExclTax(BigDecimal supplyPriceExclTax) {
        this.supplyPriceExclTax = supplyPriceExclTax;
    }


    @Column(name="MARKUP_PRCT", nullable=false, precision=8, scale=5)
    public BigDecimal getMarkupPrct() {
        return this.markupPrct;
    }
    
    public void setMarkupPrct(BigDecimal markupPrct) {
        this.markupPrct = markupPrct;
    }


    @Column(name="REORDER_POINT")
    public Integer getReorderPoint() {
        return this.reorderPoint;
    }
    
    public void setReorderPoint(Integer reorderPoint) {
        this.reorderPoint = reorderPoint;
    }


    @Column(name="REORDER_AMOUNT", precision=20)
    public BigDecimal getReorderAmount() {
        return this.reorderAmount;
    }
    
    public void setReorderAmount(BigDecimal reorderAmount) {
        this.reorderAmount = reorderAmount;
    }


    @Column(name="CURRENT_INVENTORY")
    public Integer getCurrentInventory() {
        return this.currentInventory;
    }
    
    public void setCurrentInventory(Integer currentInventory) {
        this.currentInventory = currentInventory;
    }


    @Column(name="NET_PRICE", precision=33, scale=11)
    public BigDecimal getNetPrice() {
        return this.netPrice;
    }
    
    public void setNetPrice(BigDecimal netPrice) {
        this.netPrice = netPrice;
    }


    @Column(name="OUTLET_NAME", length=100)
    public String getOutletName() {
        return this.outletName;
    }
    
    public void setOutletName(String outletName) {
        this.outletName = outletName;
    }


    @Column(name="OUTLET_ASSOCICATION_ID", nullable=false)
    public int getOutletAssocicationId() {
        return this.outletAssocicationId;
    }
    
    public void setOutletAssocicationId(int outletAssocicationId) {
        this.outletAssocicationId = outletAssocicationId;
    }


    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="BRAND_NAME", length=200)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }


    @Column(name="PRODUCT_TYPE", length=200)
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }


    @Column(name="CONTACT_NAME", length=200)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }


    @Column(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public int getCompanyAssociationId() {
        return this.companyAssociationId;
    }
    
    public void setCompanyAssociationId(int companyAssociationId) {
        this.companyAssociationId = companyAssociationId;
    }


    @Column(name="STOCK_VALUE", precision=30)
    public BigDecimal getStockValue() {
        return this.stockValue;
    }
    
    public void setStockValue(BigDecimal stockValue) {
        this.stockValue = stockValue;
    }


    @Column(name="RETAIL_VALUE", precision=43, scale=11)
    public BigDecimal getRetailValue() {
        return this.retailValue;
    }
    
    public void setRetailValue(BigDecimal retailValue) {
        this.retailValue = retailValue;
    }


    @Column(name="TOTAL_STOCK_SENT", precision=32, scale=0)
    public BigDecimal getTotalStockSent() {
        return this.totalStockSent;
    }
    
    public void setTotalStockSent(BigDecimal totalStockSent) {
        this.totalStockSent = totalStockSent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InventoryDetailReportId) ) return false;
		 InventoryDetailReportId castOther = ( InventoryDetailReportId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getProductName()==castOther.getProductName()) || ( this.getProductName()!=null && castOther.getProductName()!=null && this.getProductName().equals(castOther.getProductName()) ) )
 && ( (this.getSku()==castOther.getSku()) || ( this.getSku()!=null && castOther.getSku()!=null && this.getSku().equals(castOther.getSku()) ) )
 && ( (this.getSupplyPriceExclTax()==castOther.getSupplyPriceExclTax()) || ( this.getSupplyPriceExclTax()!=null && castOther.getSupplyPriceExclTax()!=null && this.getSupplyPriceExclTax().equals(castOther.getSupplyPriceExclTax()) ) )
 && ( (this.getMarkupPrct()==castOther.getMarkupPrct()) || ( this.getMarkupPrct()!=null && castOther.getMarkupPrct()!=null && this.getMarkupPrct().equals(castOther.getMarkupPrct()) ) )
 && ( (this.getReorderPoint()==castOther.getReorderPoint()) || ( this.getReorderPoint()!=null && castOther.getReorderPoint()!=null && this.getReorderPoint().equals(castOther.getReorderPoint()) ) )
 && ( (this.getReorderAmount()==castOther.getReorderAmount()) || ( this.getReorderAmount()!=null && castOther.getReorderAmount()!=null && this.getReorderAmount().equals(castOther.getReorderAmount()) ) )
 && ( (this.getCurrentInventory()==castOther.getCurrentInventory()) || ( this.getCurrentInventory()!=null && castOther.getCurrentInventory()!=null && this.getCurrentInventory().equals(castOther.getCurrentInventory()) ) )
 && ( (this.getNetPrice()==castOther.getNetPrice()) || ( this.getNetPrice()!=null && castOther.getNetPrice()!=null && this.getNetPrice().equals(castOther.getNetPrice()) ) )
 && ( (this.getOutletName()==castOther.getOutletName()) || ( this.getOutletName()!=null && castOther.getOutletName()!=null && this.getOutletName().equals(castOther.getOutletName()) ) )
 && (this.getOutletAssocicationId()==castOther.getOutletAssocicationId())
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && this.getCreatedDate().equals(castOther.getCreatedDate()) ) )
 && ( (this.getBrandName()==castOther.getBrandName()) || ( this.getBrandName()!=null && castOther.getBrandName()!=null && this.getBrandName().equals(castOther.getBrandName()) ) )
 && ( (this.getProductType()==castOther.getProductType()) || ( this.getProductType()!=null && castOther.getProductType()!=null && this.getProductType().equals(castOther.getProductType()) ) )
 && ( (this.getContactName()==castOther.getContactName()) || ( this.getContactName()!=null && castOther.getContactName()!=null && this.getContactName().equals(castOther.getContactName()) ) )
 && (this.getCompanyAssociationId()==castOther.getCompanyAssociationId())
 && ( (this.getStockValue()==castOther.getStockValue()) || ( this.getStockValue()!=null && castOther.getStockValue()!=null && this.getStockValue().equals(castOther.getStockValue()) ) )
 && ( (this.getRetailValue()==castOther.getRetailValue()) || ( this.getRetailValue()!=null && castOther.getRetailValue()!=null && this.getRetailValue().equals(castOther.getRetailValue()) ) )
 && ( (this.getTotalStockSent()==castOther.getTotalStockSent()) || ( this.getTotalStockSent()!=null && castOther.getTotalStockSent()!=null && this.getTotalStockSent().equals(castOther.getTotalStockSent()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getProductName() == null ? 0 : this.getProductName().hashCode() );
         result = 37 * result + ( getSku() == null ? 0 : this.getSku().hashCode() );
         result = 37 * result + ( getSupplyPriceExclTax() == null ? 0 : this.getSupplyPriceExclTax().hashCode() );
         result = 37 * result + ( getMarkupPrct() == null ? 0 : this.getMarkupPrct().hashCode() );
         result = 37 * result + ( getReorderPoint() == null ? 0 : this.getReorderPoint().hashCode() );
         result = 37 * result + ( getReorderAmount() == null ? 0 : this.getReorderAmount().hashCode() );
         result = 37 * result + ( getCurrentInventory() == null ? 0 : this.getCurrentInventory().hashCode() );
         result = 37 * result + ( getNetPrice() == null ? 0 : this.getNetPrice().hashCode() );
         result = 37 * result + ( getOutletName() == null ? 0 : this.getOutletName().hashCode() );
         result = 37 * result + this.getOutletAssocicationId();
         result = 37 * result + ( getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode() );
         result = 37 * result + ( getBrandName() == null ? 0 : this.getBrandName().hashCode() );
         result = 37 * result + ( getProductType() == null ? 0 : this.getProductType().hashCode() );
         result = 37 * result + ( getContactName() == null ? 0 : this.getContactName().hashCode() );
         result = 37 * result + this.getCompanyAssociationId();
         result = 37 * result + ( getStockValue() == null ? 0 : this.getStockValue().hashCode() );
         result = 37 * result + ( getRetailValue() == null ? 0 : this.getRetailValue().hashCode() );
         result = 37 * result + ( getTotalStockSent() == null ? 0 : this.getTotalStockSent().hashCode() );
         return result;
   }   


}


