package com.dowhile;
// Generated Jun 8, 2017 2:41:51 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoiceDetail generated by hbm2java
 */
@Entity
@Table(name="invoice_detail"
    ,catalog="ecom"
)
public class InvoiceDetailCustom  implements java.io.Serializable {


     public Integer getInvoiceDetailId() {
		return invoiceDetailId;
	}
	public void setInvoiceDetailId(Integer invoiceDetailId) {
		this.invoiceDetailId = invoiceDetailId;
	}
	public Integer getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	public Integer getProductId() {
		return productId;
	}
	public void setProductId(Integer productId) {
		this.productId = productId;
	}
	public Integer getProductVariantId() {
		return productVariantId;
	}
	public void setProductVariantId(Integer productVariantId) {
		this.productVariantId = productVariantId;
	}
	public Integer getOutletId() {
		return outletId;
	}
	public void setOutletId(Integer outletId) {
		this.outletId = outletId;
	}
	public Integer getInvoiceMainId() {
		return invoiceMainId;
	}
	public void setInvoiceMainId(Integer invoiceMainId) {
		this.invoiceMainId = invoiceMainId;
	}
	public BigDecimal getItemRetailPrice() {
		return itemRetailPrice;
	}
	public void setItemRetailPrice(BigDecimal itemRetailPrice) {
		this.itemRetailPrice = itemRetailPrice;
	}
	public BigDecimal getItemSalePrice() {
		return itemSalePrice;
	}
	public void setItemSalePrice(BigDecimal itemSalePrice) {
		this.itemSalePrice = itemSalePrice;
	}
	public BigDecimal getItemDiscountPrct() {
		return itemDiscountPrct;
	}
	public void setItemDiscountPrct(BigDecimal itemDiscountPrct) {
		this.itemDiscountPrct = itemDiscountPrct;
	}
	public BigDecimal getItemTaxAmount() {
		return itemTaxAmount;
	}
	public void setItemTaxAmount(BigDecimal itemTaxAmount) {
		this.itemTaxAmount = itemTaxAmount;
	}
	public BigDecimal getItemOrignalAmt() {
		return itemOrignalAmt;
	}
	public void setItemOrignalAmt(BigDecimal itemOrignalAmt) {
		this.itemOrignalAmt = itemOrignalAmt;
	}
	public String getItemNotes() {
		return itemNotes;
	}
	public void setItemNotes(String itemNotes) {
		this.itemNotes = itemNotes;
	}
	public int getProductQuantity() {
		return productQuantity;
	}
	public void setProductQuantity(int productQuantity) {
		this.productQuantity = productQuantity;
	}
	public Timestamp getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}
	public Timestamp getLastUpdated() {
		return lastUpdated;
	}
	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
	public Integer getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}
	public Integer getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
	public boolean isIsreturn() {
		return isreturn;
	}
	public void setIsreturn(boolean isreturn) {
		this.isreturn = isreturn;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public String getVarientAttributeName() {
		return varientAttributeName;
	}
	public void setVarientAttributeName(String varientAttributeName) {
		this.varientAttributeName = varientAttributeName;
	}
	private Integer invoiceDetailId;
     private Integer companyId;
     private Integer productId;
     private Integer productVariantId;
     private Integer outletId;
     private Integer invoiceMainId;
     private BigDecimal itemRetailPrice;
     private BigDecimal itemSalePrice;
     private BigDecimal itemDiscountPrct;
     private BigDecimal itemTaxAmount;
     private BigDecimal itemOrignalAmt;
     private String itemNotes;
     private int productQuantity;
     private Timestamp createdDate;
     private Timestamp lastUpdated;
     private Integer createdBy;
     private Integer updatedBy;
     private boolean isreturn;
     private String productName;
     private String varientAttributeName;

}


