package com.dowhile;

// Generated Dec 23, 2017 11:28:11 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageDetail generated by hbm2java
 */
@Entity
@Table(name = "message_detail")
public class MessageDetail implements java.io.Serializable {

	private Integer messageDetailId;
	private Outlet outlet;
	private Company company;
	private Message message;
	private String senderId;
	private String receiverId;
	private String messageDescription;
	private byte[] deliveryId;
	private String deliveryStatus;
	private boolean activeIndicator;
	private Date createdDate;
	private Date lastUpdated;
	private Integer createdBy;
	private Integer updatedBy;

	public MessageDetail() {
	}

	public MessageDetail(Company company, Message message,
			boolean activeIndicator, Date createdDate, Date lastUpdated) {
		this.company = company;
		this.message = message;
		this.activeIndicator = activeIndicator;
		this.createdDate = createdDate;
		this.lastUpdated = lastUpdated;
	}

	public MessageDetail(Outlet outlet, Company company, Message message,
			String senderId, String receiverId, String messageDescription,
			byte[] deliveryId, String deliveryStatus, boolean activeIndicator,
			Date createdDate, Date lastUpdated, Integer createdBy,
			Integer updatedBy) {
		this.outlet = outlet;
		this.company = company;
		this.message = message;
		this.senderId = senderId;
		this.receiverId = receiverId;
		this.messageDescription = messageDescription;
		this.deliveryId = deliveryId;
		this.deliveryStatus = deliveryStatus;
		this.activeIndicator = activeIndicator;
		this.createdDate = createdDate;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MESSAGE_DETAIL_ID", unique = true, nullable = false)
	public Integer getMessageDetailId() {
		return this.messageDetailId;
	}

	public void setMessageDetailId(Integer messageDetailId) {
		this.messageDetailId = messageDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUTLET_ASSOCICATION_ID")
	public Outlet getOutlet() {
		return this.outlet;
	}

	public void setOutlet(Outlet outlet) {
		this.outlet = outlet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ASSOCIATION_ID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MESSAGE_ASSOCIATION_ID", nullable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@Column(name = "SENDER_ID", length = 256)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "RECEIVER_ID", length = 256)
	public String getReceiverId() {
		return this.receiverId;
	}

	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	@Column(name = "MESSAGE_DESCRIPTION", length = 1000)
	public String getMessageDescription() {
		return this.messageDescription;
	}

	public void setMessageDescription(String messageDescription) {
		this.messageDescription = messageDescription;
	}

	@Column(name="DELIVERY_ID")
	   public byte[] getDeliveryId() {
	       return this.deliveryId;
	   }
	   
	   public void setDeliveryId(byte[] deliveryId) {
	       this.deliveryId = deliveryId;
	   }

	@Column(name = "DELIVERY_STATUS", length = 1000)
	public String getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(String deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	@Column(name = "ACTIVE_INDICATOR", nullable = false)
	public boolean isActiveIndicator() {
		return this.activeIndicator;
	}

	public void setActiveIndicator(boolean activeIndicator) {
		this.activeIndicator = activeIndicator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
