package com.dowhile;
// Generated Jun 8, 2017 2:41:51 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receipt generated by hbm2java
 */

public class ReceiptCustom  implements java.io.Serializable {


     public Integer getReceiptId() {
		return receiptId;
	}
	public void setReceiptId(Integer receiptId) {
		this.receiptId = receiptId;
	}
	public Integer getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	public Integer getOutletId() {
		return outletId;
	}
	public void setOutletId(Integer outletId) {
		this.outletId = outletId;
	}
	public Integer getContactId() {
		return contactId;
	}
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}
	public Integer getPaymentTypeId() {
		return paymentTypeId;
	}
	public void setPaymentTypeId(Integer paymentTypeId) {
		this.paymentTypeId = paymentTypeId;
	}
	public Integer getDailyRegisterId() {
		return dailyRegisterId;
	}
	public void setDailyRegisterId(Integer dailyRegisterId) {
		this.dailyRegisterId = dailyRegisterId;
	}
	public Integer getInvoiceMainId() {
		return invoiceMainId;
	}
	public void setInvoiceMainId(Integer invoiceMainId) {
		this.invoiceMainId = invoiceMainId;
	}
	public Integer getStatusId() {
		return statusId;
	}
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}
	public String getReceiptRefNo() {
		return receiptRefNo;
	}
	public void setReceiptRefNo(String receiptRefNo) {
		this.receiptRefNo = receiptRefNo;
	}
	public Timestamp getReceiptDate() {
		return receiptDate;
	}
	public void setReceiptDate(Timestamp receiptDate) {
		this.receiptDate = receiptDate;
	}
	public BigDecimal getReceiptAmount() {
		return receiptAmount;
	}
	public void setReceiptAmount(BigDecimal receiptAmount) {
		this.receiptAmount = receiptAmount;
	}
	public String getReceiptCancellationDate() {
		return receiptCancellationDate;
	}
	public void setReceiptCancellationDate(String receiptCancellationDate) {
		this.receiptCancellationDate = receiptCancellationDate;
	}
	public BigDecimal getReceiptUafAmt() {
		return receiptUafAmt;
	}
	public void setReceiptUafAmt(BigDecimal receiptUafAmt) {
		this.receiptUafAmt = receiptUafAmt;
	}
	public boolean isActiveIndicator() {
		return activeIndicator;
	}
	public void setActiveIndicator(boolean activeIndicator) {
		this.activeIndicator = activeIndicator;
	}
	public Timestamp getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}
	public Timestamp getLastUpdated() {
		return lastUpdated;
	}
	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
	public Integer getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}
	public Integer getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
	private Integer receiptId;
     private Integer companyId;
     private Integer outletId;
     private Integer contactId;
     private Integer paymentTypeId;
     private Integer dailyRegisterId;
     private Integer invoiceMainId;
     private Integer statusId;
     private String receiptRefNo;
     private Timestamp receiptDate;
     private BigDecimal receiptAmount;
     private String receiptCancellationDate;
     private BigDecimal receiptUafAmt;
     private boolean activeIndicator;
     private Timestamp createdDate;
     private Timestamp lastUpdated;
     private Integer createdBy;
     private Integer updatedBy;

   
}


