package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockOrderDetail generated by hbm2java
 */
@Entity
@Table(name="stock_order_detail"
    ,catalog="ecom"
)
public class StockOrderDetail  implements java.io.Serializable {


     private Integer stockOrderDetailId;
     private ProductVariant productVariant;
     private Company company;
     private StockOrder stockOrder;
     private Product product;
     private boolean isProduct;
     private Integer orderProdQty;
     private BigDecimal ordrSupplyPrice;
     private Integer recvProdQty;
     private BigDecimal recvSupplyPrice;
     private BigDecimal retailPrice;
     private boolean activeIndicator;
     private Date createdDate;
     private Date lastUpdated;
     private Integer createdBy;
     private Integer updatedBy;

    public StockOrderDetail() {
    }

	
    public StockOrderDetail(Company company, StockOrder stockOrder, boolean isProduct, boolean activeIndicator, Date createdDate, Date lastUpdated) {
        this.company = company;
        this.stockOrder = stockOrder;
        this.isProduct = isProduct;
        this.activeIndicator = activeIndicator;
        this.createdDate = createdDate;
        this.lastUpdated = lastUpdated;
    }
    public StockOrderDetail(ProductVariant productVariant, Company company, StockOrder stockOrder, Product product, boolean isProduct, Integer orderProdQty, BigDecimal ordrSupplyPrice, Integer recvProdQty, BigDecimal recvSupplyPrice, BigDecimal retailPrice, boolean activeIndicator, Date createdDate, Date lastUpdated, Integer createdBy, Integer updatedBy) {
       this.productVariant = productVariant;
       this.company = company;
       this.stockOrder = stockOrder;
       this.product = product;
       this.isProduct = isProduct;
       this.orderProdQty = orderProdQty;
       this.ordrSupplyPrice = ordrSupplyPrice;
       this.recvProdQty = recvProdQty;
       this.recvSupplyPrice = recvSupplyPrice;
       this.retailPrice = retailPrice;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STOCK_ORDER_DETAIL_ID", unique=true, nullable=false)
    public Integer getStockOrderDetailId() {
        return this.stockOrderDetailId;
    }
    
    public void setStockOrderDetailId(Integer stockOrderDetailId) {
        this.stockOrderDetailId = stockOrderDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_VARIANT_ASSOCICATION_ID")
    public ProductVariant getProductVariant() {
        return this.productVariant;
    }
    
    public void setProductVariant(ProductVariant productVariant) {
        this.productVariant = productVariant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STOCK_ORDER_ASSOCICATION_ID", nullable=false)
    public StockOrder getStockOrder() {
        return this.stockOrder;
    }
    
    public void setStockOrder(StockOrder stockOrder) {
        this.stockOrder = stockOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ASSOCIATION_ID")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="IS_PRODUCT", nullable=false)
    public boolean isIsProduct() {
        return this.isProduct;
    }
    
    public void setIsProduct(boolean isProduct) {
        this.isProduct = isProduct;
    }

    
    @Column(name="ORDER_PROD_QTY")
    public Integer getOrderProdQty() {
        return this.orderProdQty;
    }
    
    public void setOrderProdQty(Integer orderProdQty) {
        this.orderProdQty = orderProdQty;
    }

    
    @Column(name="ORDR_SUPPLY_PRICE", precision=20)
    public BigDecimal getOrdrSupplyPrice() {
        return this.ordrSupplyPrice;
    }
    
    public void setOrdrSupplyPrice(BigDecimal ordrSupplyPrice) {
        this.ordrSupplyPrice = ordrSupplyPrice;
    }

    
    @Column(name="RECV_PROD_QTY")
    public Integer getRecvProdQty() {
        return this.recvProdQty;
    }
    
    public void setRecvProdQty(Integer recvProdQty) {
        this.recvProdQty = recvProdQty;
    }

    
    @Column(name="RECV_SUPPLY_PRICE", precision=20)
    public BigDecimal getRecvSupplyPrice() {
        return this.recvSupplyPrice;
    }
    
    public void setRecvSupplyPrice(BigDecimal recvSupplyPrice) {
        this.recvSupplyPrice = recvSupplyPrice;
    }

    
    @Column(name="RETAIL_PRICE", precision=20)
    public BigDecimal getRetailPrice() {
        return this.retailPrice;
    }
    
    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }

    
    @Column(name="ACTIVE_INDICATOR", nullable=false)
    public boolean isActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(boolean activeIndicator) {
        this.activeIndicator = activeIndicator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


