package com.dowhile;
// Generated Aug 17, 2017 1:48:25 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockOrder generated by hbm2java
 */
@Entity
@Table(name="stock_order"
    ,catalog="ecom"
)
public class StockOrder  implements java.io.Serializable {


     private Integer stockOrderId;
     private Outlet outletByOutletAssocicationId;
     private Company company;
     private Outlet outletBySourceOutletAssocicationId;
     private Status status;
     private StockOrderType stockOrderType;
     private String stockRefNo;
     private Date diliveryDueDate;
     private int contactId;
     private String orderNo;
     private String contactInvoiceNo;
     private Date stockOrderDate;
     private String remarks;
     private Date ordrRecvDate;
     private String returnNo;
     private boolean autofillReorder;
     private boolean retailPriceBill;
     private boolean activeIndicator;
     private Date createdDate;
     private Date lastUpdated;
     private Integer createdBy;
     private Integer updatedBy;
     private Set<StockOrderDetail> stockOrderDetails = new HashSet<StockOrderDetail>(0);

    public StockOrder() {
    }

	
    public StockOrder(Outlet outletByOutletAssocicationId, Company company, Status status, StockOrderType stockOrderType, Date diliveryDueDate, int contactId, boolean autofillReorder, boolean retailPriceBill, boolean activeIndicator, Date createdDate, Date lastUpdated) {
        this.outletByOutletAssocicationId = outletByOutletAssocicationId;
        this.company = company;
        this.status = status;
        this.stockOrderType = stockOrderType;
        this.diliveryDueDate = diliveryDueDate;
        this.contactId = contactId;
        this.autofillReorder = autofillReorder;
        this.retailPriceBill = retailPriceBill;
        this.activeIndicator = activeIndicator;
        this.createdDate = createdDate;
        this.lastUpdated = lastUpdated;
    }
    public StockOrder(Outlet outletByOutletAssocicationId, Company company, Outlet outletBySourceOutletAssocicationId, Status status, StockOrderType stockOrderType, String stockRefNo, Date diliveryDueDate, int contactId, String orderNo, String contactInvoiceNo, Date stockOrderDate, String remarks, Date ordrRecvDate, String returnNo, boolean autofillReorder, boolean retailPriceBill, boolean activeIndicator, Date createdDate, Date lastUpdated, Integer createdBy, Integer updatedBy, Set<StockOrderDetail> stockOrderDetails) {
       this.outletByOutletAssocicationId = outletByOutletAssocicationId;
       this.company = company;
       this.outletBySourceOutletAssocicationId = outletBySourceOutletAssocicationId;
       this.status = status;
       this.stockOrderType = stockOrderType;
       this.stockRefNo = stockRefNo;
       this.diliveryDueDate = diliveryDueDate;
       this.contactId = contactId;
       this.orderNo = orderNo;
       this.contactInvoiceNo = contactInvoiceNo;
       this.stockOrderDate = stockOrderDate;
       this.remarks = remarks;
       this.ordrRecvDate = ordrRecvDate;
       this.returnNo = returnNo;
       this.autofillReorder = autofillReorder;
       this.retailPriceBill = retailPriceBill;
       this.activeIndicator = activeIndicator;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.stockOrderDetails = stockOrderDetails;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STOCK_ORDER_ID", unique=true, nullable=false)
    public Integer getStockOrderId() {
        return this.stockOrderId;
    }
    
    public void setStockOrderId(Integer stockOrderId) {
        this.stockOrderId = stockOrderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OUTLET_ASSOCICATION_ID", nullable=false)
    public Outlet getOutletByOutletAssocicationId() {
        return this.outletByOutletAssocicationId;
    }
    
    public void setOutletByOutletAssocicationId(Outlet outletByOutletAssocicationId) {
        this.outletByOutletAssocicationId = outletByOutletAssocicationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPANY_ASSOCIATION_ID", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SOURCE_OUTLET_ASSOCICATION_ID")
    public Outlet getOutletBySourceOutletAssocicationId() {
        return this.outletBySourceOutletAssocicationId;
    }
    
    public void setOutletBySourceOutletAssocicationId(Outlet outletBySourceOutletAssocicationId) {
        this.outletBySourceOutletAssocicationId = outletBySourceOutletAssocicationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ASSOCICATION_ID", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STOCK_ORDER_TYPE_ASSOCICATION_ID", nullable=false)
    public StockOrderType getStockOrderType() {
        return this.stockOrderType;
    }
    
    public void setStockOrderType(StockOrderType stockOrderType) {
        this.stockOrderType = stockOrderType;
    }

    
    @Column(name="STOCK_REF_NO", length=45)
    public String getStockRefNo() {
        return this.stockRefNo;
    }
    
    public void setStockRefNo(String stockRefNo) {
        this.stockRefNo = stockRefNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DILIVERY_DUE_DATE", nullable=false, length=10)
    public Date getDiliveryDueDate() {
        return this.diliveryDueDate;
    }
    
    public void setDiliveryDueDate(Date diliveryDueDate) {
        this.diliveryDueDate = diliveryDueDate;
    }

    
    @Column(name="CONTACT_ID", nullable=false)
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    
    @Column(name="ORDER_NO", length=45)
    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    
    @Column(name="CONTACT_INVOICE_NO", length=45)
    public String getContactInvoiceNo() {
        return this.contactInvoiceNo;
    }
    
    public void setContactInvoiceNo(String contactInvoiceNo) {
        this.contactInvoiceNo = contactInvoiceNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STOCK_ORDER_DATE", length=19)
    public Date getStockOrderDate() {
        return this.stockOrderDate;
    }
    
    public void setStockOrderDate(Date stockOrderDate) {
        this.stockOrderDate = stockOrderDate;
    }

    
    @Column(name="REMARKS", length=500)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ORDR_RECV_DATE", length=19)
    public Date getOrdrRecvDate() {
        return this.ordrRecvDate;
    }
    
    public void setOrdrRecvDate(Date ordrRecvDate) {
        this.ordrRecvDate = ordrRecvDate;
    }

    
    @Column(name="RETURN_NO", length=45)
    public String getReturnNo() {
        return this.returnNo;
    }
    
    public void setReturnNo(String returnNo) {
        this.returnNo = returnNo;
    }

    
    @Column(name="AUTOFILL_REORDER", nullable=false)
    public boolean isAutofillReorder() {
        return this.autofillReorder;
    }
    
    public void setAutofillReorder(boolean autofillReorder) {
        this.autofillReorder = autofillReorder;
    }

    
    @Column(name="RETAIL_PRICE_BILL", nullable=false)
    public boolean isRetailPriceBill() {
        return this.retailPriceBill;
    }
    
    public void setRetailPriceBill(boolean retailPriceBill) {
        this.retailPriceBill = retailPriceBill;
    }

    
    @Column(name="ACTIVE_INDICATOR", nullable=false)
    public boolean isActiveIndicator() {
        return this.activeIndicator;
    }
    
    public void setActiveIndicator(boolean activeIndicator) {
        this.activeIndicator = activeIndicator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stockOrder")
    public Set<StockOrderDetail> getStockOrderDetails() {
        return this.stockOrderDetails;
    }
    
    public void setStockOrderDetails(Set<StockOrderDetail> stockOrderDetails) {
        this.stockOrderDetails = stockOrderDetails;
    }




}


