USE `ecom`;

ALTER TABLE price_book_detail
MODIFY  COLUMN SUPPLY_PRICE DECIMAL(20,2) NOT NULL,
MODIFY COLUMN  MARKUP DECIMAL(8,5) NOT NULL,
MODIFY COLUMN  DISCOUNT DECIMAL(8,5) NOT NULL;

ALTER TABLE price_book
ADD COLUMN FLAT_SALE VARCHAR(6) NOT NULL Default 'false',
ADD COLUMN  FLAT_DISCOUNT DECIMAL(8,5) NOT NULL Default 0.00;

DROP VIEW IF EXISTS Price_Book_Detail_Summary;
CREATE VIEW Price_Book_Detail_Summary AS 
SELECT 
PRICE_BOOK_DETAIL_ID,PRICE_BOOK_ASSOCICATION_ID,PRODUCT_ASSOCICATION_ID,
(select PRODUCT_NAME from ecom.product where PRODUCT_ID=PRODUCT_ASSOCICATION_ID)as 'PRODUCT_NAME',
IFNULL(PRODUCT_VARIENT_ASSOCICATION_ID,0) as PRODUCT_VARIENT_ASSOCICATION_ID,
COALESCE((select VARIANT_ATTRIBUTE_NAME from ecom.product_variant where PRODUCT_VARIANT_ID=PRODUCT_VARIENT_ASSOCICATION_ID),'-' )as 'VARIANT_ATTRIBUTE_NAME',
SUPPLY_PRICE,MARKUP,DISCOUNT,CREATED_BY,UPDATED_BY,SALES_TAX_ASSOCIATION_ID,COMPANY_ASSOCIATION_ID
from ecom.price_book_detail where ACTIVE_INDICATOR="1";

-- ------Added new sales user
ALTER TABLE `ecom`.`invoice_main` 
ADD COLUMN `SALES_USER` INT(11) NULL AFTER `PAYMENT_TYPE_ASSOCICATION_ID`;
