USE `ecom`;
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('4','Ecom Administrator','Ecom Admin',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('5','Ecom Customer','Ecom Customer',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into user (USER_EMAIL,PASSWORD,ROLE_ASSOCIATION_ID,FIRST_NAME,LAST_NAME,CONTACT_ASSOCICATION_ID,OUTLET_ASSOCICATION_ID,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,LAST_LOGIN,COMPANY_ASSOCIATION_ID)
	values ('ecom_admin@shopvitals.com','ecom_admin','4','Ecom','Admin',null,null,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP,1);
