USE `ecom`;

insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlet',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);

delete FROM `ecom`.menu WHERE  MENU_NAME ='outlet';