
-- AUTHOR : Team(DOWHILE)
-- CREATION DATE : 31-DEC-2016
-- UPDATION DATE : 18-FEB-2017
-- -------------------------Printer Format---Test-------------
INSERT INTO printer_format (PRINTER_FORMAT_ID ,PRINTER_FORMAT_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'Continuous Feed', 1, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, 1, 1);



INSERT INTO printer_format (PRINTER_FORMAT_ID, PRINTER_FORMAT_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES ( 2,'Continuous Feed-Wide', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


-- ---------------------Currency------------

INSERT INTO currency ( CURRENCY_ID,CURRENCY_NAME, CURRENCY_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'Rupees', 'PKR', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);



INSERT INTO currency ( CURRENCY_ID,CURRENCY_NAME, CURRENCY_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES ( 2,'Dollar', 'USD', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


-- -------------------Time Zone-------------------------


INSERT INTO time_zone (TIME_ZONE_ID, TIME_ZONE_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, '(GMT+05:00)Asia/Karachi', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

-- -------------------Role-------------------------

insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('1','Administrator','Admin',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('2','Manager','Manager',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('3','Cashier','Cashier',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- -------------------Severity-------------------------

insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('1','HIGH');
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('2','MEDIUM');
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('3','LOW');
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('4','NORMAL');

-- ----------Company----------------------



INSERT INTO company (COMPANY_NAME, DISPLAY_PRICES, SKU_GENERATION, CURRENT_SEQUENCE_NUMBER, LOYALTY_ENABLED, LOYALTY_INVOICE_AMOUNT, LOYALTY_AMOUNT, LOYALTY_ENABLED_DATE, USER_SWITCH_SECURITY, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY, PRINTER_ASSOCICATION_ID, CURRENCY_ASSOCICATION_ID, TIME_ZONE_ASSOCICATION_ID,LOYALTY_BONUS_ENABLED_DATE,LOYALTY_BONUS_AMOUNT,LOYALTY_BONUS_ENABLED,ENABLE_STORES_CREDIT)
VALUES ('Hadia Fashion', 'Tax Inclusive', 'Generate By Name', '10000', 0, 5000, 50, CURRENT_TIMESTAMP, 'Never require a password when switching between users', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 1, 1, 1,CURRENT_TIMESTAMP,0.00,1,'false');



-- ---------------user--------------

insert into user (USER_EMAIL,PASSWORD,ROLE_ASSOCIATION_ID,FIRST_NAME,LAST_NAME,CONTACT_ASSOCICATION_ID,OUTLET_ASSOCICATION_ID,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,LAST_LOGIN,COMPANY_ASSOCIATION_ID)
	values ('umair@shopvitals.com','123','1','Umair','Javed',null,null,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,CURRENT_TIMESTAMP,1);


-- -----------------Outlet---------------------------

-- INSERT INTO outlet ( OUTLET_ID,ACTIVE_IND, OUTLET_NAME, SELS_TAX_PERCENTAGE, CREATED_BY, CREATED_DATE, UPDATED_BY, LAST_UPDATED,COMPANY_ASSOCICATION_ID)
-- VALUES ( 1,1, 'First_Outlet', 5.5, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP,1);


-- -----------------Register---------------------------
-- insert into REGISTER (REGISTER_ID,REGISTER_NAME,CACHE_MANAGEMENT_ENABLE,RECEIPT_NUMBER,RECEIPT_PREFIX,RECEIPT_SUFIX,SELECT_NEXT_USER_FOR_SALE,EMAIL_RECEIPT,PRINT_RECEIPT,NOTES,PRINT_NOTES_ON_RECEIPT,SHOW_DISCOUNT_ON_RECEIPT,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,OUTLET_ASSOCICATION_ID,COMPANY_ASSOCICATION_ID)
--	values (1,'Main Register','No','RECEIPT_NUMBER','RECEIPT_PREFIX','RECEIPT_SUFIX','SELECT_NEXT_USER_FOR_SALE','EMAIL_RECEIPT','PRINT_RECEIPT','NOTES','PRINT_NOTES_ON_RECEIPT','SHOW_DISCOUNT_ON_RECEIPT',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1,1);

-- -------------------Country-------------


INSERT INTO country ( COUNTRY_ID,COUNTRY_NAME, ACTIVE_INDICATOR, CREATED_BY, CREATED_DATE, UPDATED_BY, LAST_UPDATED)
VALUES ( 1,'Pakistan', 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- -------------------Menu-------------
-- ===================================== Role ID = 1 (Admin) ======================================
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('brands',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('status',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('cashManagement',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('companySetup',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customerDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customerGroup',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customers',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ecommerce',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ecomProducts',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('home',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('layoutDesign',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('loyalty',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageCustomer',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageOutlet',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageProduct',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageRegister',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newCustomer',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newPriceBook',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newProduct',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newSupplier',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newUser',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('orders',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlet',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlets',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('paymentType',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('poCreateandReceive',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('poCreateandReceiveEdit',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
	insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('priceBook',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('products',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productTags',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productType',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
	insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrder',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderActions',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderEditDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderEditProducts',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderReceive',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('register',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('registerClose',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('roleDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('roles',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesHistory',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesLedger',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesTax',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('sell',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockControl',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturn',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnActions',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnEditDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnEditProducts',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransfer',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferActions',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferEditDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferEditProducts',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('store',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('storeCredit',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('suppliers',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('users',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageRole',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('support',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ticketActivity',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageUser',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('printLabels',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('supplierDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesReport',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('companySetupImages',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outletPaymentDetails',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('orgHierarchy',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('managePriceBook',1,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);

-- ===================================== Role ID = 2 (Manager) ======================================

insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('brands',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('status',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('cashManagement',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('companySetup',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customerDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customerGroup',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customers',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ecommerce',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ecomProducts',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('home',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('layoutDesign',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('loyalty',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageCustomer',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageOutlet',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageProduct',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageRegister',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newCustomer',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newPriceBook',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newProduct',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newSupplier',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newUser',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('orders',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlet',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlets',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('paymentType',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('poCreateandReceive',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('poCreateandReceiveEdit',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('priceBook',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('products',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productTags',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productType',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrder',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderActions',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderEditDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderEditProducts',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderReceive',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('register',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('registerClose',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('roleDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('roles',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesHistory',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesLedger',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesTax',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('sell',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockControl',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturn',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnActions',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnEditDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnEditProducts',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransfer',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferActions',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferEditDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferEditProducts',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('store',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('storeCredit',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('suppliers',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('users',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageRole',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('support',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ticketActivity',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageUser',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('printLabels',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('supplierDetails',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesReport',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('companySetupImages',2,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('managePriceBook',2,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
-- ===================================== Role ID = 3 (Cashier) ======================================
	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('brands',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('status',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('cashManagement',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('companySetup',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customerDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customerGroup',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('customers',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ecommerce',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ecomProducts',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('home',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('layoutDesign',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('loyalty',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageCustomer',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageOutlet',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageProduct',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageRegister',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newCustomer',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newPriceBook',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newProduct',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newSupplier',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('newUser',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('orders',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlet',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('outlets',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('paymentType',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('poCreateandReceive',3,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('poCreateandReceiveEdit',3,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('priceBook',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('products',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productTags',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('productType',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrder',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderActions',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderEditDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderEditProducts',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('purchaseOrderReceive',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('register',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('registerClose',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('roleDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('roles',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesHistory',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesLedger',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesTax',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('sell',3,'Page',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockControl',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturn',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnActions',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnEditDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockReturnEditProducts',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransfer',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferActions',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferEditDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('stockTransferEditProducts',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('store',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('storeCredit',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('suppliers',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('users',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageRole',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('support',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('ticketActivity',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('manageUser',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('printLabels',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('supplierDetails',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('salesReport',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('companySetupImages',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
insert into menu (MENU_NAME,ROLE_ASSOCIATION_ID,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
	values ('managePriceBook',3,'Page',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);	
	-- -------------------Sales Tax-------------

INSERT INTO sales_tax (SALES_TAX_NAME,SALES_TAX_PERCENTAGE,EFFECTIVE_DATE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED,CREATED_BY,UPDATED_BY,COMPANY_ASSOCIATION_ID)
values ('No Tax',0,CURRENT_DATE,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);




-- -------------------address-----------------------------------
INSERT INTO address ( ADDRESS_TYPE, CONTACT_NAME, FIRST_NAME, LAST_NAME, EMAIL, PHONE, FAX, WEBSITE, TWITTER, STREET, SUBURB, CITY, POSTAL_CODE, STATE, COUNTY, X_COORDINATE, Y_COORDINATE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY, COMPANY_ASSOCIATION_ID, CONTACT_ASSOCICATION_ID, COUNTRY_ASSOCICATION_ID)

VALUES ( "Physical Address", "Umair Javed", "", "", "abcd@gmail.com", "", "23424", "www.hadiaFashion.com", "twiter", "", "Suburb", "Lahore", "234234", "Punjab", "Pakistan", 0, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 1, NULL, NULL);


-- -------------------status-----------------------------------
INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'Init', 'Initiated', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (2, 'Inp', 'In Progress', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (3, 'Comp', 'Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (4, 'Rtn', 'Returned', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (5, 'Sett', 'Settled', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (6, 'New', 'New', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (7, 'Open', 'Open', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (8, 'Close', 'Closed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (9, 'LayBy', 'LayBy', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (10, 'Compl', 'Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);



INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (11, 'Park', 'Parked', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (12, 'onAcc', 'OnAccount', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (13, 'LyCom', 'Lay By Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (14, 'reCmp', 'Returned Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


-- -------------------stock_order_type-----------------------------------
INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'SO', 'Supplier Order', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (2, 'SR', 'Supplier Return', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (3, 'OT', 'Outlet Transfer', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);



-- -------------------payment_type-----------------------------------
INSERT INTO payment_type (`PAYMENT_TYPE_ID`, `PAYMENT_TYPE_VALUE`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`)
 VALUES ('1', 'Cash', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO payment_type (PAYMENT_TYPE_VALUE, ROUND_TO, GATEWAY, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES ('Credit Card', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL);



-- -------------------customer_group-----------------------------------
INSERT INTO contact_group ( CONTACT_GROUP_ID,CONTACT_GROUP_NAME, COUNTRY_ASSOCICATION_ID, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY,COMPANY_ASSOCIATION_ID)
VALUES (1, 'All Contact', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1,1);
-- ---------------------------------outlet---------------------------------

INSERT INTO outlet (OUTLET_NAME, ORDER_NUMBER, ORDER_NUMBER_PREFIX, CONTACT_NUMBER_PREFIX, CONTACT_RETURN_NUMBER, COMPANY_ASSOCIATION_ID, SALES_TAX_ASSOCICATION_ID, ADDRESS_ASSOCICATION_ID, TIME_ZONE_ASSOCICATION_ID, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY,IS_HEAD_OFFICE)
VALUES ( 'Main Outlet', '100', 'Main Outlet', 'temp', '4', 1, 1, null, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1,TRUE);

-- ------------------------------Main Register --------------------------
INSERT INTO `ecom`.`register` (`REGISTER_NAME`, `CACHE_MANAGEMENT_ENABLE`, `RECEIPT_NUMBER`, `RECEIPT_PREFIX`, `RECEIPT_SUFIX`, `SELECT_NEXT_USER_FOR_SALE`, `EMAIL_RECEIPT`, `PRINT_RECEIPT`, `NOTES`, `PRINT_NOTES_ON_RECEIPT`, `SHOW_DISCOUNT_ON_RECEIPT`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CREATED_BY`, `UPDATED_BY`, `OUTLET_ASSOCICATION_ID`, `COMPANY_ASSOCIATION_ID`) VALUES ('Main Register', 'Yes', '1', '1', '1', 'No', 'No', 'Yes', 'On Save/Layby/Account/Return', 'No', 'Yes', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', '1', '1');

-- ----------------------------------User_Outlet-------------------------
INSERT INTO user_outlets (`USER_OUTLETS_ID`, `COMPANY_ASSOCIATION_ID`, `USER_ASSOCIATION_ID`, `OUTLET_ASSOCICATION_ID`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CREATED_BY`, `UPDATED_BY`) VALUES ('1', '1', '1', '1', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1');
insert into configuration (CONFIGURATION_ID,PROPERTY_NAME,PROPERTY_VALUE,COMPANY_ASSOCIATION_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,LAST_UPDATED,ACTIVE_INDICATOR) values ('1','DOCUMENTS_PATH','/var/lib/openshift/58a851df89f5cfe479000018/app-root/data/userFiles','1','1','1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
-- insert into CONFIGURATION (PROPERTY_NAME,PROPERTY_VALUE,COMPANY_ASSOCIATION_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,LAST_UPDATED) values ('DOCUMENTS_PATH','C://sv//data',1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- -------------------------contact_payments_type-------------------------
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('1', 'CUSTOMER');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('2', 'SUPPLIER');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('3', 'EMPLOYEE');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('4', 'OTHERS');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('5', 'OUTLET');

-- ----------------------------User Outlet Update------------------------
UPDATE `ecom`.`user` SET `OUTLET_ASSOCICATION_ID`='1' WHERE `USER_ID`='1';
-- -------------------------Contacts--------------------------------------
INSERT INTO `ecom`.`contact` (`CONTACT_NAME`, `CONTACT_BALANCE`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CONTACT_OUTLET_ID`, `CREATED_BY`, `COMPANY_ASSOCIATION_ID`,CONTACT_GROUP_ASSOCIATION_ID) VALUES ('Main Outlet', '0.00000', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', '1','1');
-- ------------------------ Kites Data -------------------------------------
INSERT INTO `ecom`.`brand` (`BRAND_NAME`, `BRAND_DESCRIPTION`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CREATED_BY`, `UPDATED_BY`, `COMPANY_ASSOCIATION_ID`) VALUES ('Kites', 'Kites', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', '1');
INSERT INTO `ecom`.`variant_attribute` (`ATTRIBUTE_NAME`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CREATED_BY`, `UPDATED_BY`, `VARIANT_ATTRIBUTE_ASSOCIATION_ID`, `COMPANY_ASSOCIATION_ID`) VALUES ( 'Color', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', '0', '1');
INSERT INTO `ecom`.`variant_attribute` (`ATTRIBUTE_NAME`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`, `CREATED_BY`, `UPDATED_BY`, `VARIANT_ATTRIBUTE_ASSOCIATION_ID`, `COMPANY_ASSOCIATION_ID`) VALUES ( 'Size', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '1', '0', '1');
