USE `ecom`;
DROP TABLE IF EXISTS `NOTIFICATION`;
CREATE TABLE NOTIFICATION(

  NOTIFICATION_ID INT NOT NULL AUTO_INCREMENT,
  OUTLET_ID_FROM INT NOT NULL,
  OUTLET_ID_TO INT NOT NULL,
  SUBJECT VARCHAR(256) NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  MARK_AS_READ BIT NOT NULL,
  COMPANY_ASSOCIATION_ID INT NOT NULL,
  ACTIVE_INDICATOR BIT NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  CREATED_BY INT NULL,
  UPDATED_BY INT NULL,
  
  CONSTRAINT `NOTIFICATION_NOTIFICATION_ID_PK` PRIMARY KEY (`NOTIFICATION_ID`),
  CONSTRAINT `NOTIFICATION_OUTLET_ID_TO_FK` FOREIGN KEY (`OUTLET_ID_TO`) REFERENCES outlet (`OUTLET_ID`),
  CONSTRAINT `NOTIFICATION_OUTLET_ID_FROM_FK` FOREIGN KEY (`OUTLET_ID_FROM`) REFERENCES outlet (`OUTLET_ID`),
  CONSTRAINT `NOTIFICATION_COMPANY_ASSOCIATION_ID_FK` FOREIGN KEY (`COMPANY_ASSOCIATION_ID`) REFERENCES company (`COMPANY_ID`)
  
);