USE `ecom`;

-- -------------------------Printer Format---Test-------------
INSERT INTO printer_format (PRINTER_FORMAT_ID ,PRINTER_FORMAT_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'Continuous Feed', 1, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, 1, 1);
INSERT INTO printer_format (PRINTER_FORMAT_ID, PRINTER_FORMAT_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES ( 2,'Continuous Feed-Wide', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);
-- ---------------------Currency------------
INSERT INTO currency ( CURRENCY_ID,CURRENCY_NAME, CURRENCY_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'Rupees', 'PKR', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);
INSERT INTO currency ( CURRENCY_ID,CURRENCY_NAME, CURRENCY_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES ( 2,'Dollar', 'USD', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);
-- -------------------Time Zone-------------------------
INSERT INTO time_zone (TIME_ZONE_ID, TIME_ZONE_VALUE, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, '(GMT+05:00)Asia/Karachi', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);
-- -------------------Role-------------------------
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('1','Administrator','Admin',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('2','Manager','Manager',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('3','Cashier','Cashier',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
-- insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('4','Ecom Administrator','Ecom Admin',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
-- insert into role (ROLE_ID,DESCRIPTION,ACTION_TYPE,ACTIVE_INDICATOR,CREATED_DATE,LAST_UPDATED) values ('5','Ecom Customer','Ecom Customer',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- -------------------Severity-------------------------
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('1','HIGH');
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('2','MEDIUM');
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('3','LOW');
insert into severity (SEVERITY_ID,SEVERITY_DESCRIPTION)	values ('4','NORMAL');
-- -------------------Country-------------
INSERT INTO country ( COUNTRY_ID,COUNTRY_NAME, ACTIVE_INDICATOR, CREATED_BY, CREATED_DATE, UPDATED_BY, LAST_UPDATED)
VALUES ( 1,'Pakistan', 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- -------------------status-----------------------------------
INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'Init', 'Initiated', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (2, 'Inp', 'In Progress', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (3, 'Comp', 'Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (4, 'Rtn', 'Returned', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (5, 'Sett', 'Settled', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (6, 'New', 'New', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (7, 'Open', 'Open', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (8, 'Close', 'Closed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (9, 'LayBy', 'LayBy', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (10, 'Compl', 'Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

-- -------------------stock_order_type-----------------------------------
INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (1, 'SO', 'Supplier Order', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (2, 'SR', 'Supplier Return', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (3, 'OT', 'Outlet Transfer', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);



-- -------------------payment_type-----------------------------------
INSERT INTO payment_type (`PAYMENT_TYPE_ID`, `PAYMENT_TYPE_VALUE`, `ACTIVE_INDICATOR`, `CREATED_DATE`, `LAST_UPDATED`)
 VALUES ('1', 'Cash', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO payment_type (PAYMENT_TYPE_VALUE, ROUND_TO, GATEWAY, ACTIVE_INDICATOR, CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES ('Credit Card', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL);

-- -------------------------contact_payments_type-------------------------
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('1', 'CUSTOMER');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('2', 'SUPPLIER');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('3', 'EMPLOYEE');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('4', 'OTHERS');
INSERT INTO `ecom`.`contact_payments_type` (`CONTACT_PAYMENT_TYPE_ID`, `CONTACT_PAYMENT_TYPE_NAME`) VALUES ('5', 'OUTLET');
-- ----------------------Stock Order Type added for Return to Warehouse

INSERT INTO stock_order_type ( STOCK_ORDER_TYPE_ID,STOCK_ORDER_TYPE_CODE, STOCK_ORDER_TYPE_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (4, 'SRW', 'Return to Warehouse', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);




INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (11, 'Park', 'Parked', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (12, 'onAcc', 'OnAccount', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (13, 'LyCom', 'Lay By Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


INSERT INTO status ( STATUS_ID,STATUS_CODE, STATUS_DESC, ACTIVE_INDICATOR, 
CREATED_DATE, LAST_UPDATED, CREATED_BY, UPDATED_BY)
VALUES (14, 'reCmp', 'Returned Completed', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);


