package com.dowhile.constants;

public class Fluffies {
	

	
//	E2E-1.1.6
		private static String  E2E_1_1_6 ="\nE2E_1_1_6\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount,"
				+ "which the Client has setup as a Percent (%), will not be rejected and a Warning will display on the IGO/NIGO Report "
				+ "PPC: $5000.00 YTD Contrib : $14500 (Limit is $18000 - $14500 = 3500) PLAN : 102374 E $4000 "
				+ "Expected Result : Warning in IGO stating contribution greater CLM Limit \n"
			+ "When OSDA run\n"
				+ "then we are expected PH see the following: Recieves a Warning Message on the UI\n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source Feedback O/P File: E $3500\n"
			+ "When CR2 is run\n"
				+ "then PS sends in the correct amount in the CR file, E $3500  1122 file: E $3500 CR Rejection Report: PH not Listed ContribDiscrip Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "then Verify that PH is listed in the FB file E $0.00 \n";
		
//	E2E-1.1.7
		private static String  E2E_1_1_7 ="\nE2E_1_1_7\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount,"
				+ " which the Client has setup as a Percent (%), will not be rejected and a Warning will display on the IGO/NIGO Report "
				+ "PPC: $5000.00 YTD Contrib : $14500 (Limit is $18000 - $14500 = 3500) PLAN : 102374 E $4000 Expected Result : Warning in IGO stating contribution greater CLM Limit \n"
			+ "When OSDA run\n"
				+ "then we are expected PH see the following: Recieves a Warning Message on the UI\n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location,"
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source Feedback O/P File: E $3500\n"
			+ "When CR2 is run\n"
				+ "PS sends in the incorrect amount in the CR file, E $4000  1122 file: E $3500 "
				+ "CR Rejection Report: PH is listed with E $500.00 402G1 Limit exceeded ContribDiscrip Report: Expected E $3500.00, Actual E $4000.00 \n"
			+ "When FB3 is run\n"
				+ "then Verify that PH is listed in the FB file E $0.00 \n";
		
//		E2E-2.1.1
		private static String  E2E_2_1_1 ="\nE2E_2_1_1\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value BELOW the Minimum Paycheck Level Contribution Constraint deferral amount,"
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report "
			+ "PPC: $5000.00 PLAN : 102374 Expected Result : Participant is not listed on IGO/NIGO report  \n"
			+ "When OSDA run\n"
				+ "then we are expected PH submits OSDA of $45.00 Recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value BELOW to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location,"
				+ "then Feedback will reduce the deferral(s) to zero from the non-matched portion of each EE voluntary source Feedback O/P File: E $0.00\n";
		
//		E2E-2.1.2
		private static String  E2E_2_1_2 ="\nE2E_2_1_2\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value BELOW the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report "
			+ "PPC: $5000.00 PLAN : 102374 E $50.00  Expected Result : Participant is not listed on IGO/NIGO report \n"
			+ "When OSDA run\n"
				+ "hen PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value EQUAL to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will NOT reduce the deferral(s) from the non-matched portion of each EE voluntary source Feedback O/P File: E $50.00\n"
			+ "When CR1 is run\n"
				+ "then we are expected PS sends in the incorrect amount in the CR file, "
				+ "E $45.00 1122 file: E $45.00 CR Rejection Report: PH NOT Listed ContribDiscrip Report: Expected E $50.00, Actual E $45.00 This is not correct."
				+ "If the contribution constraints are being enforeced on the CR file, "
				+ "the Contribution of $45 would be rejected and the rejection report would show E $45 with the reason, "
				+ "Outside of Paycheck level Contribution Constraints -- Min Constraints are not enforced on CR file I would think there would also be a discrepancy report showing Expected $50 and Actual $45\n"
			+ "When FB2 is run\n"
				+ "then Verify PH is NOT listed in the FB O/P File\n";
		
//		E2E-2.1.3
		private static String  E2E_2_1_3 ="\nE2E_2_1_3\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value BELOW the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report "
			+ "PPC: $5000.00 PLAN : 102374 E $50.00 Expected Result : Participant is not listed on IGO/NIGO report \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value EQUAL to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will NOT reduce the deferral(s) from the non-matched portion of each EE voluntary source Feedback O/P File: E $50.00\n"
			+ "When CR1 is run\n"
				+ "then we are expected PS sends in the incorrect amount in the CR file, E $45.00 1122 file: E $45.00 "
				+ "CR Rejection Report: PH isListed ContribDiscrip Report: Expected E $50.00, Actual E $45.00 This is not correct.   "
				+ "If the contribution constraints are being enforeced on the CR file, "
				+ "the Contribution of $45 would be rejected and the rejection report would show E $45 with the reason, "
				+ "Outside of Paycheck level Contribution Constraints -- Min Constraints are not enforced on CR file I would think there would also be a discrepancy report showing Expected $50 and Actual $45\n"
			+ "When FB2 is run\n"
				+ "then Verify PH is NOT listed in the FB O/P File\n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for E $5.00 This implies, 1% of PPC = $50 Adjustment Record Accepted "
				+ "1122 File: PH is listed with Contribution Amount $5.00 CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
		
//		E2E-2.1.4
		
		private static String  E2E_2_1_4 ="\nE2E_2_1_4\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value BELOW the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report "
			+ "PPC: $5000.00 PLAN : 102374 E $150.00 Expected Result : Participant is not listed on IGO/NIGO report \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value EQUAL to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will NOT reduce the deferral(s) from the non-matched portion of each EE voluntary source Feedback O/P File: E $150.00\n"
			+ "When CR1 is run\n"
				+ "then we are expected PS sends in the incorrect amount in the CR file, E $150.00 1122 file: E $150.00 "
				+ "CR Rejection Report: PH is NOT listed ContribDiscrip Report: Ph is NOT listed \n"
			+ "When FB2 is run\n"
				+ "then Verify PH is NOT listed in the FB O/P File\n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for E -$100.00 This implies, 1% of PPC = $50 "
				+ "Adjustment Record Accepted 1122 File: PH is listed with Contribution Amount E -$100 CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-3.1.0
		private static String  E2E_3_1_0 ="\nE2E_3_1_0\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report "
			+ "With the match 1 - 5 % - D -> 100% Plan Dependency : Intent to MAX 403(b) "
			+ "PPC: $5000.00 YTD(403b) : $16200 [CLM Limit = $18000.00 - $16200 = 1800) # Pay Period : 1 PLAN : 102373 (403b) E $2000"
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b) E $2000 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750)\n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source Reduce for Contrib Constraints"
				+ "PPC = $5000 Constraint: 75% * $5000 = $3750 Combined Contributions: $2000(403b) + $2000(457) = $4000 Reduction Amount $4000 - $3750 = $250"
				+ "PLAN 103273 Feedback O/P File: E $1883.33 Match Portion: $5000 * 5% = $250 Non-Match Portion: $2000 - $250 = $1750 $1750 / $3750 = 0.466667"
				+ "$250 * 0.466667 = $116.67 $2000 - $116.67 = $1883.33 PLAN 103276 Feedback O/P File: E $1866.67 Non-Match Portion $2000 $2000 / $3750 = 0.533333"
				+ "$250 * 0.533333 = $133.33 $2000 - $133.33 = $1866.67 $1883.33(403b) + $1866.67(457) = $3750.00 THEN Reduce for CLM for 403(b)"
				+ "PLAN 103273 Feedback O/P File: E $1800.00 CLM: $18000(Limit) - $16200(PreviousContrib) = $1800.00 $1883.33(ProRata) - $1800.00(Limit) = $83.33"
				+ "PLAN 103276 Feedback O/P File: E $1950.00 since 403(b) is reduced for CLM, we need to check if the difference can be added to the 457(b)."
				+ "$1866.67 + $83.33 = $1950.00 Check: $1800.00(403b) + $1950.00(457) = $3750.00 \n"
			+ "When CR1 is run\n"
				+ "then we are expected PS sends in the incorrect amount in the CR file, E $150.00 1122 file: E $150.00 "
				+ "CR Rejection Report: PH is NOT listed ContribDiscrip Report: Ph is NOT listed \n"
			+ "When FB2 is run\n"
				+ "then Verify PH is NOT listed in the FB O/P File\n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for E -$100.00 This implies, 1% of PPC = $50 "
				+ "Adjustment Record Accepted 1122 File: PH is listed with Contribution Amount E -$100 CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-3.1.1
		private static String  E2E_3_1_1 ="\nE2E_3_1_1\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report With the match 1 - 5 % - D -> 100%"
			+ "Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500] "
			+ "# Pay Period : 2 PLAN : 102373 (403b) E $2000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750)"
			+ "PLAN : 102376 (457b) E $2000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source PLAN 103273 Feedback O/P File: E $1883.33"
				+ "PLAN 103276 Feedback O/P File: E $1866.67\n"
			+ "When CR2 is run\n"
				+ "PS sends in the correct amount in the CR file PLAN:103273 E $1883.33 1122 file: E $1883.33 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed "
				+ "PLAN:103276 E $ 1866.67 1122 file: E $1866.67 CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103273 E $1616.67 Plan: 103276 E $2000.00 \n";
//		E2E-3.1.2
		private static String  E2E_3_1_2 ="\nE2E_3_1_2\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report "
			+ "Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500] "
			+ "# Pay Period : 2 PLAN : 102374 (403b) E $3000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750)"
			+ "PLAN : 102376 (457b) E $1000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+ "Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 102374 Feedback O/P File: E $2812.50 PLAN 102376 Feedback O/P File: E - $937.50\n"
			+ "When CR2 is run\n"
				+ "PS sends in the incorrect amount in the CR file  PLAN: 103274 E $1875 1122 file: E $1875 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: Expected E $2812.50, Actual E $1875.00"
				+ "PLAN: 103276 E $1875 1122 file: E $1875 CR Rejection Report: PH not listed ContribDiscrip Report: Expected E $937.50, Actual E $1875.00  \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $1625.00 Plan: 103276 E $1000.00\n";
//		E2E-3.1.3
		private static String  E2E_3_1_3 ="\nE2E_3_1_3\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "ER Match rule in Plan 102373 of 1-5% across Src. E and 2 with a Match of 100% in Src. D Plan Dependency : Intent to MAX 403(b)"
			+ "PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500] "
			+ "# Pay Period : 2 PLAN : 102373 (403b) E $3000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750)"
			+ "PLAN : 102376 (457b) E $1000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750)\n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source "
				+ "PLAN 103273 Feedback O/P File: E $2816.67 PLAN 103276 Feedback O/P File: E - 933.33\n"
			+ "When CR2 is run\n"
				+ "PS sends in the incorrect amount in the CR file PLAN: 103273 E $3000.00 1122 file: E $2816.67 "
				+ "CR Rejection Report: PH is listed with E $183.33 Outside of Paycheck Level Contribution Constraint "
				+ "ContribDiscrip Report: Expected E $2816.67, Actual E $3000.00 PLAN: 103276 E $1000.00 1122 file: E $933.33 "
				+ "CR Rejection Report: PH is listed with E $66.67  Outside of Paycheck Level Contribution Constraint ContribDiscrip Report: Expected E $933.33, Actual E $1000.00 \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103273 E $683.33 Plan: 103276 E $1000.00 \n";
//		E2E-3.1.4
		private static String  E2E_3_1_4 ="\nE2E_3_1_4\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500]"
			+ "# Pay Period : 2 PLAN : 102374 (403b) E $3000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750)"
			+ "PLAN : 102376 (457b) E $1000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "	PLAN 102374 Feedback O/P File: E $2812.50 PLAN 102376 Feedback O/P File: E - 937.50\n"
			+ "When CR2 is run\n"
				+ "PS sends in the incorrect amount in the CR file PLAN: 102374 E $3000.00 1122 file: E $2812.50 "
				+ "CR Rejection Report: PH is listed with E $187.50 Outside of Paycheck Level Contribution Constraint"
				+ "ContribDiscrip Report: Expected E $2812.50, Actual E $3000.00 PLAN: 102376 E $1000.00 1122 file: E $ 937.50"
				+ "CR Rejection Report: PH is listed with E $62.50 Outside of Paycheck Level Contribution Constraint"
				+ "ContribDiscrip Report: Expected E $937.50, Actual E $1000.00 \n"
			+ "When Adjustment file is run\n"
				+ "Adj reductions are taken only on the adjusted amount and not the whole contribution. T"
				+ "here fore the 1122 file would have Plan: 102373 1122 File: E $0.00 "
				+ "CR Rejection Report: PH is listed with E $187.50 Outside of Paycheck Level Contribution Constraint"
				+ "Plan: 102376 1122 File: E $0.00 CR Rejection Report: PH is listed with E $62.50 Outside of Paycheck Level Contribution Constraint\n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $687.50 Plan: 103276 E $1000.00 \n";
//		E2E-3.1.4.1
		private static String  E2E_3_1_4_1 ="\nE2E_3_1_4_1\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Assumes the participant is eligible for the Match of 1-5% in E and 2 with a 100% match in D.. Plan Dependency : Intent to MAX 403(b)"
			+ "PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500] "
			+ "# Pay Period : 2 PLAN : 102373 (403b) E $2000 PLAN : 102376 (457b) E $1000 \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 102373 Feedback O/P File: E $2000 PLAN 102376 Feedback O/P File: E $1000\n"
			+ "When CR2 is run\n"
				+ "PS sends in the incorrect amount in the CR file PLAN: 102373 E $2000.00 1122 file: E $2000.00 "
				+ "CR Rejection Report: PH not listed PLAN: 102376 E $1000.00 1122 file: E $ 1000.00 CR Rejection Report: PH not listed \n"
			+ "When Adjustment file is run\n"
				+ "Run an Adjustment for 403(b)  E $500 and 457(b) E $500 Adj reductions are taken only on the adjusted amount and not the whole contribution."
				+ "Plan: 102373 1122 File: E $375.00 CR Rejection Report: PH is listed with E $125.00 Outside of Paycheck Level Contribution Constraint"
				+ "Plan: 102376 1122 File: E $375.00 CR Rejection Report: PH is listed with E $125.00 Outside of Paycheck Level Contribution Constraint\n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103273 E $1125.00 Plan: 103276 Not listed (same as previous feedback)\n";
//		E2E-3.1.5
		private static String E2E_3_1_5 ="\nE2E_3_1_5\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Assumes the participant is not yet eligible for the Match. Plan Dependency : Intent to MAX 403(b)"
			+ "	PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500] "
			+ "# Pay Period : 2 PLAN : 102374 (403b) E $2000.00 Expected Result : No Warning in IGO since the contribution is less then 75% ($3750)"
			+ "PLAN : 102376 (457b) E $1000.00 Expected Result : No Warning in IGO since the contribution is less then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Muliple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 102374 Feedback O/P File: E $2000.00 PLAN 102376 Feedback O/P File: E $1000.00\n"
			+ "When CR2 file is run\n"
				+ "PS sends in the incorrect amount in the CR file, PLAN: 102374 E $2000.00 1122 file: E $2000.00 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed PLAN: 102376 E $1000.00 1122 file: E $1000.00 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed \n"
			+ "When Adjustment file is run\n"
				+ "Run an Adjustment for E Adj reductions are taken only on the adjusted amount and not the whole contribution."
				+ "Adjustment Record Accepted, but Contributions will be pratical accepted/rejected 1122 File: PH is listed and adjustement is partically accepted/rejected"
				+ "PLAN:102374 E $800.00 1122 file: E $600.00 CR Rejection Report: PH is listed with E $200.00 Outside of Paycheck Level Contribution Constraint"
				+ "PLAN:102376 E $200.00 1122 file: E $150.00 CR Rejection Report: PH is listed with E $50.00 Outside of Paycheck Level Contribution Constraint\n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $900.00 Plan: 103276 Not listed (same as previous feedback)\n";
//		E2E-3.1.6
		private static String E2E_3_1_6 ="\nE2E_3_1_6\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Assumes the participant is not yet eligible for the Match. Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500]"
			+ "	# Pay Period : 2 PLAN : 102374 (403b) E $3000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750)"
			+ "PLAN : 102376 (457b) E $1000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 102374 Feedback O/P File: E $2812.50 PLAN 102374 Feedback O/P File: E $937.50\n"
			+ "When CR2 file is run\n"
				+ "PS sends in the incorrect amount in the CR file PLAN: 102374 E $3750 1122 file: E  $2960.53 "
				+ "CR Rejection Report: PH is listed with E $789.47 Outside of Paycheck Level Contribution Constraint"
				+ "ContribDiscrip Report: Expected E $2812.50, Actual E $3750.00 PLAN: 102374 E $1000 1122 file: E $789.47 "
				+ "CR Rejection Report: PH is listed with E $210.53 Outside of Paycheck Level Contribution Constraint "
				+ "ContribDiscrip Report: Expected E $937.50, Actual E $1000.00 \n"
			+ "When Adjustment file is run\n"
				+"Run an Adjustment for E Adj reductions are taken only on the adjusted amount and not the whole contribution."
				+ "	Adjustment Record Rejected 1122 File: PH is listed and adjustement is partical accepted/rejected"
				+ "PLAN:102374 E $1000.00 1122 file: E $0.00 CR Rejection Report: PH is listed with E $1000.00 Outside of Paycheck Level Contribution Constraint"
				+ "PLAN:102376 E $200.00 1122 file: E $0.00 CR Rejection Report: PH is listed with E $200.00 Outside of Paycheck Level Contribution Constraint\n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $539.47 Plan: 103276 E $1000.00 \n";
//		E2E-3.1.7
		private static String E2E_3_1_7 ="\nE2E_3_1_7\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Assuming participant is not yet eligible for the Match PPC: $5000.00 PLAN : 102374 (403b) E $4000 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b) E $1000 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750)\n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 102374 Feedback O/P File: E $3000.00 PLAN 102376 Feedback O/P File: E $750.00\n"
			+ "When CR2 file is run\n"
				+ "PS sends in the correct amount in the CR file PLAN: 102374 E $4000 1122 file: E $3000.00 "
				+ "CR Rejection Report: PH is listed with E $1000.00 Outside of Paycheck Level Contribution Constraint"
				+ "ContribDiscrip Report: Expected E $3000.00, Actual E $3750.00 PLAN: 102376 E $1000 1122 file: E $750.00 "
				+ "CR Rejection Report: PH is listed with E $250.00 Outside of Paycheck Level Contribution Constraint"
				+ "ContribDiscrip Report: Expected E $750.00, Actual E $1000.00 \n"
			+ "When Adjustment file is run\n"
				+"Run an Adjustment for E Adjustment Record Rejected 1122 File: PH is listed and adjustement is rejected PLAN:103274 E $1000.00 1122 file: E $0.00 "
				+ "CR Rejection Report: PH not listed PLAN:103276 E - Not present 1122 file:  PH not listed CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $500.00 Plan: 103276 E $1000.00 \n";
//		E2E-3.1.8
		private static String E2E_3_1_8 ="\nE2E_3_1_8\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Assume Participant is not yet eligible for the match Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500]"
			+ "# Pay Period : 2 PLAN : 102374 (403b) E $2000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b) E $2000"
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source PLAN 103274 "
				+ "Feedback O/P File: E $1875 PLAN 103276 Feedback O/P File: E $1875\n"
			+ "When CR2 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103274 E $1875 1122 file: E $1875 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed  PLAN: 103276 E $1875 1122 file: E $1875 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed \n"
			+ "When Adjustment file is run\n"
				+"Run an Adjustment for E PPC: $6000.00 Adjustment Record Accepted, PPC is change but Contributions will not change"
				+ "Plan: 103274 1122 File: PH is listed and adjustement is accepted: PPC $6000.00 "
				+ "CR Rejection Report: PH not listed Plan: 103276 1122 File: PH is listed and adjustement is accepted: PPC $6000.00 CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $1625.00 Plan: 103276 E $2000.00 \n";
//		E2E-3.1.9
		private static String E2E_3_1_9 ="\nE2E_3_1_9\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $14500 [CLM Limit = $18000.00 - $14500 = $3500] "
			+ "# Pay Period : 2 PLAN : 102374 (403b) E $2000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b) E $2000"
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Recieves NO Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ " PLAN 103274 Feedback O/P File: E $1875 PLAN 103276 Feedback O/P File: E $1875\n"
			+ "When CR2 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103274 E $1875 1122 file: E $1875 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed PLAN: 103276 E $1875 1122 file: E $1875 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed \n"
			+ "When Adjustment file is run\n"
				+"Run an Adjustment for E PPC: $6000.00 Adjustment Record Accepted, PPC is changed and Contributions aret changed"
				+ "1122 File: PH is listed and adjustement is accepted PLAN:103274 E $125.00, PPC $6000.00 1122 file: E not listed, PPC $6000.00"
				+ "CR Rejection Report: PH not listed PLAN:103276 E $125.00, PPC $6000.00 1122 file: E not listed, PPC $6000.00 CR Rejection Report: PH not listed  \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $1500.00 Plan: 103276 E $2000.00 \n";
//		E2E-3.1.10
		private static String E2E_3_1_10 ="\nE2E_3_1_10\n"
				
			+ "A SEED file Given:ppt is $1,000 away from both 402G and 457 limits and paycheck constraint is set up with max of 75%"
			+ "	and ppt gives 2,000 contrib to 402G plan and 1500 contrib to 457b plan and ppt has ppc of 4200 	then, after paycheck constraint reduction, "
			+ "the ppt will have $1200 in the 402G plan and $900 in the 457 plan (for the total of 2100) when CLM happens, 200 will be rejected from the 402G plan,"
			+ " which means that 200 could be added back to the 457 plan but now, there is $1100 in the 457 plan, "
			+ "which will put the ppt over the limit.> = So, we'd need to put the 'restored' money back through CLM, right?> 402g happens before 457 test, "
			+ "and we might want to do this restoring after 402g. And we are doing this restoring only in the case of intent to max right?\n"
			
			+"When FB1 is run\n"
				+"PLAN 103273 Feedback O/P File: E $1000 PLAN 103276 Feedback O/P File: E $1000\n";
//		E2E-4.1.1
		private static String E2E_4_1_1 ="\nE2E_4_1_1\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value BELOW the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ " PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $25 "
			+ "Expected Result : Warning in IGO With warning that deferral is less than Min Paycheck level Contribution Constraint. "
			+ " PLAN : 102376 (457b) E $20 Expected Result : Warning in IGO With warning that deferral is less than Min Paycheck level Contribution Constraint. \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source PLAN 103273 "
				+ "Feedback O/P File: E $0.00 PLAN 103276 Feedback O/P File: E $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103273 E $25 1122 file: E $25.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $25.00 PLAN: 1032746 E $25 1122 file: E $25.00"
				+ " CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $25.00 \n"
			+ "When FB2 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-4.1.2
		private static String E2E_4_1_2 ="\nE2E_4_1_2\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value EQUAL the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $25 "
			+ "Expected Result : No Warning in IGO stating contribution PLAN : 102376 (457b) E $25 Expected Result : No Warning in IGO stating contribution \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 103273 Feedback O/P File: E $0.00 PLAN 103276 Feedback O/P File: E $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103273 E $25 1122 file: E $25.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $25.00 PLAN: 103276 E $25 1122 file: E $25.00"
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $25.00 \n"
			+ "When FB2 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-4.1.3
		private static String E2E_4_1_3 ="\nE2E_4_1_3\n"
				
			+ "A Seed file has an Employee record that submits a Dollar value EQUAL the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ " PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $20, 2 $20 "
			+ "Expected Result : No Warning in IGO stating contribution PLAN : 102376 (457b) E $10 Expected Result : No Warning in IGO stating contribution  \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ " PLAN 103273 Feedback O/P File: E $0.00, 2 $0.00 PLAN 103276 Feedback O/P File: $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the incorrect amount in the CR file  PLAN: 103273 E $15, 2 $15 1122 file:  E $15.00, 2 $15.00 "
				+ "CR Rejection Report: PH NOT is listed ContribDiscrip Report: Expected E $0.00, 2 $0.00, Actual E $15.00, 2 $15.00 PLAN: 103276 E $10 1122 file: E $10.00"
				+ "CR Rejection Report: PH NOT is listed ContribDiscrip Report: Expected E $0.00, Actual E $10.00 \n"
			+ "When FB2 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-4.1.4
		private static String E2E_4_1_4 ="\nE2E_4_1_4\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value Equal to the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ "PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $20, 2 $20 Expected Result : No Warning in IGO stating contribution"
			+ "PLAN : 102376 (457b) E $10 Expected Result : No Warning in IGO stating contribution   \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ "PLAN 103273 Feedback O/P File: E $0.00, 2 $0.00 PLAN 103276 Feedback O/P File: $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103273 E $20, 2 $20 1122 file: E $20.00, 2 $20.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, 2 $0.00, Actual E $20.00, 2 $20.00 PLAN: 103276 E $10 1122 file: E $10.00"
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $10.00  \n"
			+ "When FB2 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-4.1.5
		private static String E2E_4_1_5 ="\nE2E_4_1_5\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value EQUAL the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ "PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $20, 2 $20 "
			+ "Expected Result : No Warning in IGO stating contribution PLAN : 102376 (457b) E $10 "
			+ "Expected Result : No Warning in IGO stating contribution \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source PLAN 103273 "
				+ "Feedback O/P File: E $0.00, 2 $0.00 PLAN 103276 Feedback O/P File: $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103273 E $20, 2 $20 1122 file: E $20.00, 2 $20.00 "
				+ "CR Rejection Report: PH is not listed "
				+ "ContribDiscrip Report: Expected E $0.00, 2 $0.00, Actual E $20.00, 2 $20.00 PLAN: 103276 E $10 1122 file: E $10.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $10.00 \n"
			+ "When FB2 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-5.1.1
		private static String E2E_5_1_1 ="\nE2E_5_1_1\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ "Assume the participant is not eligible for the Match. Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $16000 [CLM Limit = $18000.00 - $16000 = $2000]"
			+ "# Pay Period : 2 PLAN : 102373 (403b) E $3000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b)"
			+ "E $1000 Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does  recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ " PLAN 103273 Feedback O/P File: E $2000 PLAN 103276 Feedback O/P File: E $1000\n"
			+ "When CR2 file is run\n"
				+"PS sends in the incorrect amount in the CR file PLAN: 103273 E $3000 1122 file: E $2000 "
				+ "CR Rejection Report: PH is listed with E $1000.50 402G1 Limit exceeded "
				+ "ContribDiscrip Report: Expected E $2000.00, Actual E $3000.00 PLAN: 103276 E $1000 1122 file: E $1000 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "Verify that PH is listed in the FB file Plan: 103274 E $0.00 Plan: 103276 Not listed\n";
//		E2E-6.1.1
		private static String E2E_6_1_1 ="\nE2E_6_1_1\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value Equal to the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ " PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102374 E $50.00 "
			+ "Expected Result : Participant is not listed on IGO/NIGO report \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value EQUAL to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will NOT reduce the deferral(s) from the non-matched portion of each EE voluntary source"
				+ " Feedback O/P File: E $50.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file, E $50.00 1122 file: E $50.00 CR Rejection Report: PH is NOT listed "
				+ "ContribDiscrip Report: PH is NOT listed \n"
			+ "When FB2 is run\n"
				+ "Verify PH is NOT listed in the FB O/P File \n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for PPC = $4000 This implies, 1% of PPC = $40 Adjustment Record Accepted 1122 file: E not listed, PPC $4000.00 "
				+ "Rejection Report: PH is not listed\n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-6.1.2
		private static String E2E_6_1_2 ="\nE2E_6_1_2\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value Equal the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ "PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102374 E $50.00 Expected Result : Participant is not listed on IGO/NIGO report  \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value EQUAL to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will NOT reduce the deferral(s) from the non-matched portion of each EE voluntary source Feedback O/P File: E $50.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the incorrect amount in the CR file, E $45.00 1122 file: E $45.00 CR Rejection Report: PH is NOT Listed "
				+ "ContribDiscrip Report: Expected E $50.00, Actual E $45.00  \n"
			+ "When FB2 is run\n"
				+ "Verify PH is NOT listed in the FB O/P File \n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for PPC = $4000 and E $45.00 This implies, 1% of PPC = $40 "
				+ "Adjustment Record Accepted 1122 file: E $45.00, PPC $4000.00 Rejection Report: PH is not listed\n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-6.1.3
		private static String E2E_6_1_3 ="\nE2E_6_1_3\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value Equal the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ "PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102374 E $50.00 "
			+ "Expected Result : Participant is not listed on IGO/NIGO report  \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value EQUAL to the Minimum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will NOT reduce the deferral(s) from the non-matched portion of each EE voluntary source Feedback O/P File: E $50.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the incorrect amount in the CR file, E $50.00 1122 file: E $50.00 "
				+ "CR Rejection Report: PH is NOT Listed ContribDiscrip Report: PH is NOT listed \n"
			+ "When FB2 is run\n"
				+ "Verify PH is NOT listed in the FB O/P File \n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for PPC = $4000 and E -$25.00 This implies, 1% of PPC = $40 "
				+ "Adjustment Record Accepted 1122 file: E $-25.00, PPC $4000.00 CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-6.5.1
		private static String E2E_6_5_1 ="\nE2E_6_5_1\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value Equal to the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ " PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $20, 2 $20 "
			+ "Expected Result : No Warning in IGO stating contribution PLAN : 102376 (457b) E $10 Expected Result : No Warning in IGO stating contribution  \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source"
				+ " PLAN 103273 Feedback O/P File: E $0.00, 2 $0.00 PLAN 103276 Feedback O/P File: $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file  PLAN: 102373 E $20, 2 $20 1122 file: E $20.00, 2 $20.00 "
				+ "CR Rejection Report: PH is not listed "
				+ "ContribDiscrip Report: Expected E $0.00, 2 $0.00, Actual E $20.00, 2 $20.00 PLAN: 102376 E $10 1122 file: E $10.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $0.00, Actual E $10.00 \n"
			+ "When FB2 is run\n"
				+ "Verify PH is NOT listed in the FB O/P File \n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for PPC = $4000 This implies, 1% of PPC = $40 "
				+ "Adjustment Record Accepted Plan:102373 1122 file: E not listed, PPC $4000.00 "
				+ "CR Rejection Report: PH not listed Plan:102376 1122 file: E not listed, PPC $4000.00 CR Rejection Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-6.5.2
		private static String E2E_6_5_2 ="\nE2E_6_5_2\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value Equal to the Minimum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be rejected and a NIGO Error will display on the IGO/NIGO Report"
			+ " PPC: $5000.00 This implies, 1% of PPC = $50 PLAN : 102373 (403b) E $20, 2 $20 "
			+ "Expected Result : No Warning in IGO stating contribution PLAN : 102376 (457b) E $10 Expected Result : No Warning in IGO stating contribution  \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value that the meets the Minimum Paycheck Level Contribution Constraint deferral amount for Multiple Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source "
				+ "PLAN 103273 Feedback O/P File: E $0.00, 2 $0.00 PLAN 103276 Feedback O/P File: $0.00\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN: 103273 E $20, 2 $20 1122 file: E $20.00, 2 $20.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: "
				+ "Expected E $0.00, 2 $0.00, Actual E $20.00, 2 $20.00 PLAN: 103276 E $10 1122 file: E $10.00 CR Rejection Report: PH is not listed "
				+ "ContribDiscrip Report: Expected E $0.00, Actual E $10.00 \n"
			+ "When FB2 is run\n"
				+ "Verify PH is NOT listed in the FB O/P File \n"
			+ "When Adjustment is run\n"
				+ "Run an Adjustment for PPC = $4000, Plan 103273 E = -$10, 2 -$10 This implies, 1% of PPC = $40 "
				+ "Adjustment Record Accepted (PPC) /Rejected (Contributions) 1122 File: PH is listed and contribution adjustement is rejected PLAN:103273 1122 file: E= -$10.00, 2 =-$10.00, PPC $4000.00 "
				+ "CR Rejection Report: PH not listed PLAN:103276 1122 file: E not listed, PPC $4000.00 CR Rejection Report: PH not listed  \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-7.1
		private static String E2E_7_1 ="\nE2E_7_1\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will not be rejected and a Warning will display on the IGO/NIGO Report"
			+ " PPC $1000.00 PLAN : 102373 E $400, 2 $400 Expected Result : Warning in IGO stating contribution greater then 75% ($750)   \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does not recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source Feedback O/P File: E $375, 2 $375 \n"
			+ "When CR2 file is run\n"
				+"PS sends in the correct amount in the CR file, E $375, 2 $375 1122 file: E $375, 2 $375 "
				+ "CR Rejection Report: PH not listed ContribDiscrip Report: PH not listed \n"
			+ "When FB3 is run\n"
				+ "PH should NOT be listed on the FB o/p file\n";
//		E2E-8.1
		private static String E2E_8_1 ="\nE2E_8_1\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ " Match rule 0-5% across E and 2 with 100% match in Src. D Plan Dependency : Intent to MAX 403(b) PPC: $5000.00 YTD(403b) : $0.00 [CLM Limit = $18000.00]"
			+ " # Pay Period : 12 PLAN : 102373 (403b) E $1500, 2: $1500 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b) E $1500 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does  recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source PLAN 103273 Feedback O/P File: E $1257.36, 2 $1257.35 PLAN 103276 "
				+ "Feedback O/P File: E $1235.29$$\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN:103273 E $1257.35, 2 $1257.35 1122 file: E $1257.35, 2 $1257.35 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Expected E $1257.36, Actual E $1257.35 PLAN:103276 E $1235.29 1122 file: E $1235.29 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Ph is not listed  \n"
			+ "When FB2 is run\n"
				+ "Verify PH is Not listed in the FB O/P File with correction \n";
//		E2E-8.2
		private static String E2E_8_2 ="\nE2E_8_2\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report"
			+ " Plan Dependency : Intent to MAX 403(b) PPC: $3500.00 YTD(403b) : $0.00 [CLM Limit = $18000.00] "
			+ "# Pay Period : 12 PLAN : 102373 (403b) E $750, 2 $750 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) PLAN : 102376 (457b) E $1500 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3750) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does  recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source PLAN 103273 Feedback O/P File: E $750, 2 $750 PLAN 103276 "
				+ "Feedback O/P File: E $1125\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file  PLAN:103273 E $750, 2 $750 1122 file: E $750, 2 $750 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Ph is not listed PLAN:103276 E $1125 1122 file: E $1125 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Ph is not listed \n"
			+ "When FB2 is run\n"
				+ "Verify PH is Not listed in the FB O/P File with correction \n";
//		E2E-8.3
		private static String E2E_8_3 ="\nE2E_8_3\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report "
			+ "Plan Dependency : Intent to MAX 403(b) PPC: $4000.00 YTD(403b) : $0.00 [CLM Limit = $18000.00] "
			+ "# Pay Period : 12 Match rule 0-5% across E and 2 with 100% match in Src. D PLAN : 102373 (403b) E $818.18, 2 $818.18 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3000) PLAN : 102376 (457b) E $1500 "
			+ "Expected Result : Warning in IGO stating contribution greater then 75% ($3000) \n"
			+ "When OSDA run\n"
				+ "then PH see the following: Does  recieves a Warning Message on the UI \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source "
				+ " PLAN 103273 Feedback O/P File: E $784.83, 2 $784.83 PLAN 103276 Feedback O/P File: E $1430.34\n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN:103273 E $818.18, 2 $818.18 1122 file: E $801.47, 2 $801.47 "
				+ "CR Rejection Report: PH is listed with E $16.71 Outside of Paycheck Level Contribution Constraint"
				+ "ContribDiscrip Report: Expected E $784.83, 2 $784.83, Actual E $828.18, 2 $818.18 PLAN:103276 E $1430.34 1122 file: E $1397.06 "
				+ "CR Rejection Report: PH is listed with E $33.28 Outside of Paycheck Level Contribution Constraint ContribDiscrip Report: Ph is not listed \n"
			+ "When FB2 is run\n"
				+ "Verify PH is Not listed in the FB O/P File with correction \n";
//		E2E-8.5
		private static String E2E_8_5 ="\nE2E_8_5\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ "which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report "
			+ " Plan Dependency : Intent to MAX 403(b) PPC: $4000.00 YTD(403b) : $0.00 [CLM Limit = $18000.00] "
			+ "# Pay Period : 12 remaining Match rule 0-5% across E and 2 with 100% match in Src. D PLAN : 102373 (403b) E $700 (43.75%), 2 $900 (56.25%) "
			+ "PLAN : 102376 (457b) E $1700  \n"
			+ "When OSDA run\n"
				+ "then Participant Elects Max \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ "then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source "
				+ " PLAN 103273 Feedback O/P File: E $656.25, 2 $843.75 PLAN 103276 Feedback O/P File: E $1500 \n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN:103273 E $656.25, 2 $843.75 1122 file: E $656.25, 2 $843.75 "
				+ "CR Rejection Report: PH is not listed "
				+ "ContribDiscrip Report: PH is not listed PLAN:103276 E $1500 1122 file: E $1500 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Ph is not listed  \n"
			+ "When FB2 is run\n"
				+ "Verify PH is Not listed in the FB O/P File with correction \n";
//		E2E-8.6
		private static String E2E_8_6 ="\nE2E_8_6\n" 
				
			+ "A Seed file has an Employee record that submits a Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount, "
			+ " which the Client has setup as a Percent (%), will be not be rejected and a Warning will display on the IGO/NIGO Report "
			+ "Plan Dependency : Intent to MAX 403(b) PPC: $4000.00 YTD(403b) : $0.00 [CLM Limit = $18000.00] "
			+ "# Pay Period : 12 remaining Match rule 0-5% across E and 2 with 100% match in Src. D PLAN : 102373 (403b) "
			+ "E $752.95 (45.55%), 2 $900 (54.45%) PLAN : 102376 (457b) E $1700 \n"
			+ "When OSDA run\n"
				+ "then Participant Elects Max \n"
			+ "When FB1 is run\n"
				+"Employee submits Dollar value ABOVE the Maximum Paycheck Level Contribution Constraint deferral amount for a Single Plan/Single Location, "
				+ " then Feedback will reduce the deferral(s) pro rata from the non-matched portion of each EE voluntary source "
				+ "PLAN 103273 Feedback O/P File: E $752.92 2 $900.03 PLAN 103276 Feedback O/P File: E $1347.05 \n"
			+ "When CR1 file is run\n"
				+"PS sends in the correct amount in the CR file PLAN:103273 E $752.92 2 $900.03 1122 file: E $752.92 2 $900.03 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: PH is not listed PLAN:103276 E $1500.00 1122 file: E $1500.00 "
				+ "CR Rejection Report: PH is not listed ContribDiscrip Report: Ph is not listed  \n"
			+ "When FB2 is run\n"
				+ "Verify PH is Not listed in the FB O/P File with correction \n";
		
		

}
